import {StudioBridgeIntentOption} from './intent-schema.ts'
import {array,boolean as bool,enumeration,integer,literal,nullable,number,object,reference,text,type InferSchema} from './dsl.ts'
const id=()=>text({minLength:1}),count=()=>integer({minimum:0}),score=()=>number({minimum:0,maximum:100})
export const INDUSTRY_LANES=['audienceAwareness','industryPrestige','commercialConfidence','output'] as const
export const INDUSTRY_FILM_LANES=['recent','critics','audience','opening','total'] as const
const StudioLaboratoryAction=object('StudioLaboratoryAction',{id:id(),label:id(),detail:text(),enabled:bool(),disabledReason:nullable(id()),intent:nullable(reference('StudioBridgeIntentOption',StudioBridgeIntentOption))})
// P13B-S1b: the S1 seat facts as data beside the existing labels. Additive only.
const StudioLaboratorySeat=object('StudioLaboratorySeat',{talentId:id(),name:id(),laboratoryFacilityId:id(),assignedWeek:count(),releasedWeek:nullable(count()),employed:bool()})
// P13B-S2: one Laboratory's own part of a stored worked week — its seats, its share of the charge, its raw output over 1/20,000.
const StudioResearchLabRow=object('StudioResearchLabRow',{laboratoryFacilityId:id(),seatTalentIds:array(id()),spend:count(),rawUnits:count()})
// `units` is the project credit over 1/160,000; `labs` is null exactly when the stored receipt has none (a single-pool week written before cooperation began).
const StudioResearchReceipt=object('StudioResearchReceipt',{week:count(),seatTalentIds:array(id()),spend:count(),units:integer({minimum:1}),labs:nullable(array(reference('StudioResearchLabRow',StudioResearchLabRow)))})
// The same per-Laboratory facts for the CURRENT quoted week; `seats` replaces the stored row's named ids.
const StudioResearchLabShare=object('StudioResearchLabShare',{laboratoryFacilityId:id(),seats:count(),spend:count(),rawUnits:count()})
const StudioResearchWeek=object('StudioResearchWeek',{ceiling:count(),usable:count(),seats:count(),output:number({minimum:0}),units:count(),labs:array(reference('StudioResearchLabShare',StudioResearchLabShare))})
// P13B-S2: one research project this Laboratory body carries — homed here or holding a seat row here.
const StudioLaboratoryProject=object('StudioLaboratoryProject',{projectId:id(),technologyId:enumeration(['synchronized-sound','lighting-control-01']),technologyLabel:id(),status:enumeration(['active','paused','cancelled','completed']),homeLaboratoryFacilityId:id(),laboratoryFacilityIds:array(id()),verifiedWork:number({minimum:0}),work:count(),budgetPerWeek:count(),progressLabel:id(),bottleneckLabel:id(),estimateLabel:id(),cooperationLabel:id(),seats:array(reference('StudioLaboratorySeat',StudioLaboratorySeat)),receipts:array(reference('StudioResearchReceipt',StudioResearchReceipt)),weekly:reference('StudioResearchWeek',StudioResearchWeek)})
const StudioLaboratoryPage=object('StudioLaboratoryPage',{buildingId:id(),title:id(),statusLabel:id(),seatLabel:id(),scientistId:nullable(id()),scientistLabel:id(),budgetLabel:id(),bottleneckLabel:id(),estimateLabel:id(),progressLabel:id(),provenanceLabel:id(),commercialLabel:id(),installationLabel:id(),actions:array(reference('StudioLaboratoryAction',StudioLaboratoryAction)),seats:array(reference('StudioLaboratorySeat',StudioLaboratorySeat)),receipts:array(reference('StudioResearchReceipt',StudioResearchReceipt)),weekly:reference('StudioResearchWeek',StudioResearchWeek),projects:array(reference('StudioLaboratoryProject',StudioLaboratoryProject))})
const StudioCampaignDate=object('StudioCampaignDate',{policy:literal('campaign-calendar-1920-52/v1'),absoluteWeek:count(),year:integer({minimum:1920}),weekOfYear:integer({minimum:1,maximum:52}),label:id()})
const StudioIndustryLane=object('StudioIndustryLane',{key:enumeration(INDUSTRY_LANES),label:id(),meaning:id(),value:number(),rank:integer({minimum:1}),priorRank:nullable(integer({minimum:1})),movement:enumeration(['new','unavailable','up','down','unchanged']),movementLabel:id(),snapshotWeek:count(),snapshotLabel:id(),priorWeek:nullable(count())})
const StudioIndustryStudio=object('StudioIndustryStudio',{studioId:id(),name:id(),mark:id(),color:id(),player:bool(),foundingLabel:id(),entryLabel:id(),recordingNotice:id(),filmCount:count(),authoredFilmCount:count(),liveFilmCount:count(),lanes:array(reference('StudioIndustryLane',StudioIndustryLane))})
const StudioIndustryFilm=object('StudioIndustryFilm',{filmId:id(),studioId:id(),studioName:id(),title:id(),genre:id(),dateLabel:id(),releaseWeek:nullable(count()),historicalYear:nullable(integer({minimum:1800,maximum:1919})),provenance:enumeration(['authored-start/v1','simulation/v1','player-record']),criticScore:score(),audienceScore:score(),openingGross:number({minimum:0}),totalGross:number({minimum:0}),runStatus:enumeration(['settled','inRun','recorded']),businessNotice:id()})
const StudioIndustryPerson=object('StudioIndustryPerson',{talentId:id(),name:id(),roleLabel:id(),employerStudioId:nullable(id()),employerName:nullable(id()),employmentLabel:id(),creditCount:count(),onPlayerLot:bool(),notice:id()})
const StudioIndustryCredit=object('StudioIndustryCredit',{talentId:id(),name:id(),role:id(),employerStudioId:nullable(id()),employerName:nullable(id())})
const StudioIndustryActivity=object('StudioIndustryActivity',{eventId:id(),week:count(),dateLabel:id(),group:enumeration(['releases','people','studios','announcements']),headline:id(),detail:id(),studioId:id(),filmId:nullable(id()),talentId:nullable(id())})
const StudioIndustryProject=object('StudioIndustryProject',{productionId:id(),studioId:id(),title:id(),genre:id(),announcedWeek:count(),dateLabel:id(),stageLabel:id(),notice:id()})
const StudioIndustryTendency=object('StudioIndustryTendency',{label:id(),detail:id(),sampleCount:count(),fromLabel:id(),throughLabel:id(),basis:id()})
export const StudioIndustrySummary=object('StudioIndustrySummary',{calendar:reference('StudioCampaignDate',StudioCampaignDate),available:bool(),playerStudioId:nullable(id()),activeStudioCount:count(),notice:id()})
export const StudioIndustryProjection=object('StudioIndustryProjection',{industry:reference('StudioIndustrySummary',StudioIndustrySummary)})
export const StudioIndustryRequest=object('StudioIndustryRequest',{protocolVersion:literal(4),schemaId:id(),sessionId:id(),requestId:id(),expectedStateRevision:count(),type:literal('industryQuery'),view:enumeration(['studios','studio','films','film','person','pulse','history','roster','project','employment','laboratory']),targetId:nullable(id()),page:count(),pageSize:integer({minimum:1,maximum:50}),lane:enumeration([...INDUSTRY_LANES,...INDUSTRY_FILM_LANES]),period:enumeration(['recent','all','authored','live'])})
export const StudioIndustryResponse=object('StudioIndustryResponse',{protocolVersion:literal(4),schemaId:id(),snapshotVersion:count(),type:literal('industryPage'),requestId:id(),sessionId:id(),stateRevision:count(),stateDigest:id(),calendar:reference('StudioCampaignDate',StudioCampaignDate),view:enumeration(['studios','studio','films','film','person','pulse','history','roster','project','employment','laboratory']),targetId:nullable(id()),page:count(),pageSize:integer({minimum:1,maximum:50}),totalRows:count(),pageCount:count(),lane:id(),period:id(),title:id(),notice:id(),studios:array(reference('StudioIndustryStudio',StudioIndustryStudio)),films:array(reference('StudioIndustryFilm',StudioIndustryFilm)),people:array(reference('StudioIndustryPerson',StudioIndustryPerson)),credits:array(reference('StudioIndustryCredit',StudioIndustryCredit)),activities:array(reference('StudioIndustryActivity',StudioIndustryActivity)),projects:array(reference('StudioIndustryProject',StudioIndustryProject)),tendencies:array(reference('StudioIndustryTendency',StudioIndustryTendency)),laboratory:nullable(reference('StudioLaboratoryPage',StudioLaboratoryPage))})
export const industryDefinitions={StudioLaboratoryAction,StudioLaboratorySeat,StudioResearchLabRow,StudioResearchReceipt,StudioResearchLabShare,StudioResearchWeek,StudioLaboratoryProject,StudioLaboratoryPage,StudioCampaignDate,StudioIndustryLane,StudioIndustryStudio,StudioIndustryFilm,StudioIndustryPerson,StudioIndustryCredit,StudioIndustryActivity,StudioIndustryProject,StudioIndustryTendency,StudioIndustrySummary,StudioIndustryProjection,StudioIndustryRequest,StudioIndustryResponse}
export type IndustryQuery=InferSchema<typeof StudioIndustryRequest>
export type IndustryPage=InferSchema<typeof StudioIndustryResponse>
export type IndustrySummary=InferSchema<typeof StudioIndustrySummary>
