from pathlib import Path
import hashlib,json,math
S=Path('/Users/zacheryspector/studio-scratch');OUT=S/'1370-c0-remaining-employment-salary-age-phase-source-proof-20261009-r1';OUT.mkdir(mode=0o700,exist_ok=True)
BASE=S/'1370-c0-remaining-employment-quote-next-slice-independent-20261009-r1';BRIDGE=S/'1370-c0-initial-quote-generated-person-source-equivalence-20261009-r1';HROOT=S/'1369-c0-preimage-replay-proposal-r7/arms/historical/tree';AROOT=S/'1370-c0-aging-era-sparse-materialized-r6-20261008-r1'
pins={};raws={}
def load(role,path,expected=None,cap=4*1024**2):
 p=Path(path);assert p.stat().st_size<=cap;b=p.read_bytes();h=hashlib.sha256(b).hexdigest();assert expected is None or h==expected,(role,h,expected);pins[role]={'path':str(p),'bytes':len(b),'sha256':h};raws[role]=b;return b
expected=json.loads(load('prior_input_pins',BASE/'INPUT-PINS.json','b23846669624467a16a2b111f7df806760e1f595338e7c6161a99d9c7a1c35a6'))
for role in ['row0_review','source_pins','H_result','H_context','F1_result','F1_context','F1_trace']:
 q=expected[role];load(role,q['path'],q['sha256']);assert len(raws[role])==q['bytes']
for role,name,sha in [('prior_final_receipt','FINAL-RECEIPT.json','712c27ec3dd5d9dec21e28150b02d24a4edec63c28b4fe9d2061f7dbbeb2192e'),('prior_facts','FACTS.json','27d72ea9903a7a6953b89768f0cd77518c6b3643c3ddb7b7aba7b2902f9124d8'),('scope_correction','SCOPE-CORRECTION.json','88e2865fd1ab3654741f9877fff5a74309ba178c8451de579d556ab989499d89')]:load(role,BASE/name,sha)
accepted_bridge_pins={x['path']:x for x in json.loads(raws['row0_review'])['pins']}
for name in ['NOTE.md','RECEIPT.json','GENERATOR-BODY-PROOF.json','SOURCE-DIFFERENCES.json']:
 entry=accepted_bridge_pins[str(BRIDGE/name)];load('bridge_'+name,BRIDGE/name,entry['sha256']);assert len(raws['bridge_'+name])==entry['bytes']
sp=json.loads(raws['source_pins']);hr=json.loads(raws['H_result']);hm=json.loads(load('H_manifest',S/'1369-c0-preimage-replay-proposal-r7/MANIFEST.json',hr['pins']['manifestSha256']))
ar=json.loads(load('A_copy_acceptance',S/'1370-c0-aging-era-sparse-r6-observed-independent-review-20261008-r1/RECEIPT.json','3a43f85ec4bd0557b6ea6ef0a46d59bfc14570324ba1297e555dee3ff4d0767d'))
ap=json.loads(load('A_copy_payload',ar['payloadPath'],ar['payloadSha256']));assert ap['sourceSha']=='3aaf55e0c06c4b745b0b722cc56913050b1ee229'
# Finite selected role blocks only: no directory inventory, source/engine imports or Git.
files=['worldgen.ts','hollywood.ts','hollywoodStartingData.ts','employment.ts','talentSummary.ts','tick.ts','hollywoodTick.ts','releaseCareers.ts','development.ts','talentMarket.ts','rng.ts','promises.ts','technology.ts','queueAdmission.ts','physicalPlans.ts','industryEmployment.ts']
for file in files:
 rel='src/core/'+file;load('H_'+file,HROOT/rel,hm['arms']['historical']['files'][rel],256*1024)
for file in ['tick.ts','aging.ts','talentMarket.ts','hollywood.ts','employment.ts']:
 rel='src/core/'+file;entry=ap['sourceManifest'][rel];load('A_'+file,AROOT/rel,entry['sha256'],256*1024);assert len(raws['A_'+file])==entry['bytes']
load('H_diagnostic',S/'1369-c0-preimage-replay-proposal-r7/diagnostic.test.ts',hr['pins']['diagnosticSha256'],32768)
# Accepted row0 pins authenticate shared creative generation and constants; no numeric draws.
for side in ['H','A']:
 for rel in ['src/core/worldgen.ts','src/core/talentSummary.ts','src/core/hollywoodStartingData.ts','src/core/employment.ts','src/core/hollywood.ts']:
  entry=sp['filesByRole'][side][rel];assert hashlib.sha256(Path(entry['path']).read_bytes()).hexdigest()==entry['sha256']
blocks=[]
def block(role,start,end,claim):
 lines=raws[role].decode().splitlines(True);end=min(end,len(lines));text=''.join(lines[start-1:end]);blocks.append({'role':role,'sourcePath':pins[role]['path'],'sourceSha256':pins[role]['sha256'],'firstLine':start,'lastLine':end,'blockSha256':hashlib.sha256(text.encode()).hexdigest(),'claim':claim,'text':text})
for args in [('H_worldgen.ts',151,177,'All four creative ROLE_BLOCKS and salaryCurve inputs: perceived primary-role skills and fame only.'),('H_worldgen.ts',447,556,'Generation stores salaryCurve after skills/fame; single role block count1 and isolated person seed; id/name replacement only.'),('H_talentSummary.ts',50,127,'Complete perceived skillVector/OVR dependency excludes age/workHistory/name/salary.'),('H_hollywood.ts',189,235,'Fresh first4 authored teams use exact role/index/id/name; max28+workHistory override leaves salaryCurve inputs intact.'),('H_hollywoodStartingData.ts',43,56,'Exact team role/index order.'),('H_tick.ts',919,943,'Industry growth occurs before terminal market; actual historical talent replacement path.'),('H_development.ts',185,198,'Developed person spread replaces only skills/genreExperience/workHistory; salary and age retained.'),('H_releaseCareers.ts',11,95,'Career producer delegates development and replaces fame only; retains other person fields and stable ids.'),('H_hollywoodTick.ts',91,151,'Staff retains existing person or appends newly generated id; no overwrite of target age/salary.'),('H_hollywoodTick.ts',234,257,'Staff precedes industry releases at old week; distinct from terminal settlement.'),('H_tick.ts',1034,1111,'Finalized state carries growth talent and incremented week; terminal market runs after growth/expiry/promises.'),('H_talentMarket.ts',227,249,'Studio ask calls shared contractOffer then optional release floor.'),('H_talentMarket.ts',287,354,'Submission proposal stores earlier quote; settlement PriceAt rederives ask at current week with premium.'),('H_talentMarket.ts',914,993,'Winner commits terms/root changes without person field edits.'),('H_talentMarket.ts',1120,1160,'Settlement rederives/commits winner before closed receipt.'),('H_talentMarket.ts',1173,1250,'Terminal market uses incremented current week; settlement last.'),('H_diagnostic',22,34,'Observer selects same receipt talentId person in returned state.'),('H_diagnostic',42,70,'Diagnostic tick only; observer after complete tick return, no actions/new generator between.'),('H_employment.ts',263,306,'Shared offer recalculates salaryCurve; fresh keyed jitter independent week/term; it does not price stored salary.'),('H_rng.ts',202,206,'Fresh seed::purpose::key derived stream.'),('A_hollywood.ts',222,241,'Provenance captures authored post-max28 fractional age before committed floor.'),('A_hollywood.ts',260,269,'Entry provenance same captured age and original week.'),('A_aging.ts',25,35,'AgeAt floor(anchor age+(week-anchorweek)/52).'),('A_tick.ts',1035,1072,'Birthday materialization occurs at new week before terminal pricing.'),('A_tick.ts',1110,1145,'Terminal market runs after age materialization, release growth and relationship/promise phases.')]:block(*args)
facts=json.loads(raws['prior_facts']);hrows=[json.loads(x) for x in raws['H_context'].splitlines()];frows=[json.loads(x) for x in raws['F1_context'].splitlines()];trace=[json.loads(x) for x in raws['F1_trace'].splitlines()];hs={x['person']['id']:(i+1,x) for i,x in enumerate(hrows) if x['week']==208};fs={x['person']['id']:(i+1,x) for i,x in enumerate(frows) if x['week']==208};assert len(hs)==len(fs)==24
salary_obs=[x for x in trace if x.get('kind')=='salary'];assert len(salary_obs)==1;known='person-studio-aca408ec-r01-0';assert salary_obs[0]['talentId']==known;assert salary_obs[0]['jitter']==0.9757723039761186
records=[]
for row in facts['records']:
 rid=row['talentId'];line,context=hs[rid];person=context['person'];assert not (row['startWeek']==208 and context['receipt']['kind']!='settled');assert line==row['H_person208_line'];assert person['role']==row['role'];assert person['age']==row['H_age208'];assert person['salary']==row['H_storedSalary208'];assert person['salary']==fs[rid][1]['person']['salary'];renew=row['startWeek']==208
 record={**row,'annualAttribution':'UNEXPLAINED_MISSING_PRICING_ROLES','inputRoles':{'seed':{'value':'p13a-core-causal-01','origin':'accepted H RESULT and common fixture/caller source bridge','phase':'generation/quote shared'},'identityRole':{'value':rid,'creativeRole':row['role'],'origin':'stable actual contract identity and exact authored team index source','phase':'generation→observer'},'initialSalaryCurve':{'value':person['salary'],'origin':'H terminal208 stored salary preserved by enumerated historical person replacement paths; common full creative generator/helper/constants source bridge','phase':'generation/pre-initial-offer scalar, transported by preservation; not evolved208 salaryCurve'},'H_initialAge':{'value':person['age'],'origin':'same H terminal208 exact fractional age; historical tick person paths preserve age after authored max28','phase':'authored entry/week0; source transport'},'A_initialAge':{'value':math.floor(person['age']),'origin':'same generated person + A committed age floor','phase':'week0 source-derived, not new capture'},'jitter':{'value':salary_obs[0]['jitter'] if rid==known else None,'origin':'accepted F1 row0 salary observation with exact common keyed offer caller' if rid==known else 'NO accepted observation for this ID; do not invert rounded salary','phase':'fresh hiring/offer-ID independent week/term'},'offerWeekTerm':{'week':row['startWeek'],'termWeeks':row['termWeeks'],'origin':'actual H/A contract terms','phase':'committed contract; initial offer0 or settlement208'}}}
 if renew:
  record['inputRoles'].update({'H_renewalAge':{'value':person['age'],'origin':'H terminal208 same person after tick return; preserves historical age','phase':'settlement208 quote input'},'A_renewalAge':{'value':math.floor(person['age']+4),'origin':'A entry fractional provenance anchor at0 and ageAt/materialization before terminal208','phase':'settlement208 source-derived; not F1 evolved person transport'},'H_renewalSalaryCurveInputs':{'valueAvailable':True,'origin':'exact H terminal208 full person perceived skills/fame; market settlement does not mutate person after quote','phase':'current settlement208 pricing vector; scalar not evaluated here'},'A_renewalSalaryCurveInputs':{'valueAvailable':False,'origin':'NO accepted aging208 full pricing state for this ID in these inputs; F1 modern film-hold context inadmissible substitute','phase':'required aging settlement208 pricing vector'},'studioFloorPremium':{'valueAvailable':'not numerically closed in this slice','origin':'shared studioOffer/proposalPriceAt call path; preserved contract terms alone do not identify all upstream factors','phase':'settlement208, distinguish persisted proposal submission quote'}})
 records.append(record)
initial={x['talentId'] for x in records if x['startWeek']==0};renew={x['talentId'] for x in records if x['startWeek']==208};missing=sorted((initial|renew)-{known});assert len(initial)==22 and len(renew)==16 and len(missing)==23;assert renew-initial=={known,'person-studio-aca408ec-r03-2'}
missing_roles=[{'talentId':rid,'purpose':'hiring','key':'offer-'+rid,'initialRequired':rid in initial,'renewalRequired':rid in renew,'acceptedMeasurement':None} for rid in missing]
proof={'schema':'1370-remaining-contract-salary-age-phase-source-proof-r1','status':'PROPOSED_SOURCE_ATTRIBUTION_REQUIRES_INDEPENDENT_REVIEW','execution':'stdlib bounded reads/hash/JSON/table only; no source imports, RNG, Node, engine, tests, game, Git or production writes','sourceRoles':{'H':'accepted r7 historical8708 source manifest','A':'accepted materialization qualified3aaf source payload; selected files only, not current whole freeze','F1':'accepted modern film-hold artifacts; only row0 measured jitter reused through accepted bridge; no evolved stats transport'},'scope':{'initialRows':22,'renewedRows':16,'distinctMissingJitterRoles':23,'newAnnualAttributions':0},'preservationArgument':'Diagnostic supplies no actions. Historical initial person receives max28/workHistory override, which cannot alter roleOVR(perceived skills)/fame salaryCurve. Enumerated tick talent path takes industry talent, preserves existing people or appends unique supply, maps releaseCareers/developTalent immutable replacements preserving age and salary, then carries same person fields through terminal roots/settlement to diagnostic. Therefore captured H stored salary and age can anchor initial pricing inputs; evolved skills/fame cannot be transported backwards. This finite source path argument does not claim every module or arbitrary action preserves person fields.','observerPhase':'H terminal context208 is post-growth, post-increment, post-settlement. PriceAt/commit winner quote at208 before observer changes employment/cash/market/promise roots without changing person. It can supply H current salaryCurve vector at settlement, not earlier persisted proposal submission quote. A materializes new-week birthday ages before terminal market; source-derived ages may be transported using common entry anchor, while missing A evolved pricing vector remains missing.','H_F1_salaryScalarAgreement24':'artifact corroboration only; no F1 evolved state substitution','knownJitter':{'talentId':known,'value':salary_obs[0]['jitter'],'reuse':'only through identical fresh stream key/call source proof; no execution'},'missingJitterRoles':missing_roles,'records':records,'claimLimit':'All38 annual quotes remain unexplained; no new historical measurement, annual cause, ledger admission, F1→A evolved fields, rounded-salary inversion, week208 unmatched-placement resolution, or current full source freeze.'}
(OUT/'PROOF.json').write_text(json.dumps(proof,indent=2)+'\n');(OUT/'SOURCE-BLOCKS.json').write_text(json.dumps(blocks,indent=2)+'\n');(OUT/'INPUT-PINS.json').write_text(json.dumps(pins,indent=2,sort_keys=True)+'\n')
(OUT/'REPORT.md').write_text('''The finite source bridge extends initial generation inputs to the remaining22 rows, while all38 annual quotes remain unexplained. PROOF.json joins exact existing contract identities/occurrences and labels each quantity by origin and phase. SOURCE-BLOCKS.json retains selected authenticated source excerpts. No source was executed and no jitter was generated or inferred.

All four creative roles use the accepted full-generator/helper/constants source-equivalence bridge, with one isolated per-ID person seed and the unchanged four-argument caller. Each initial authored team slot supplies the same role/id/name. Initial Hollywood overrides only age via max28, workHistory, and the A committed age floor. salaryCurve reads primary perceived-role skills and fame; roleOVR reads the perceived skill vector and constants, excluding age/workHistory/name. Thus each generated stored salary remains the exact initial salaryCurve after overrides, even though this stored scalar becomes stale for later actual skills/fame.

Historical preservation follows the actual diagnostic's tick-only person flow. staff retains existing person references or appends new unique supplied people. applyReleaseCareers and developTalent create spread replacements changing skills, genre experience, work history and fame; they preserve the historical fractional age and stored salary. tick carries this resulting talent list to its incremented state; terminal market commitment changes employment and other roots, not the person. This argument covers the enumerated reached tick person replacement path, not arbitrary actions/all source modules. The24 historical terminal208 persons independently join the actual IDs; stored salary matches F1 for24 as corroboration, with no backward transport of evolved F1 skills/fame.

The observer runs after the complete tick returns. H renewal settlement PriceAt recalculates current salaryCurve through studioOffer/contractOffer/offerForTalent at208, after release growth and tick increment, and commits before terminal context is emitted. Therefore H terminal208 full person is usable as the settlement pricing vector. A persisted proposal's submission salary is an earlier quote and must not be conflated with this settlement price. A tick materializes birthdays for new week before terminal pricing. A initial age=floor(H authored entry age); A208 age=floor(H entry age+4) follows its captured-at-entry fractional provenance source law. These are source-derived roles, not fresh measurements. Aging208 evolved perceived skills/fame remain unavailable for16 renewal prices; F1 modern film-hold state does not supply them.

The common fresh stream is seed::hiring::offer-ID, independent of week/term and prior draws. Only row0 jitter0.9757723039761186 is measured in accepted F1 trace and reusable through the accepted bridge. The missing list is exactly23 distinct IDs:22 changed initial people plus r03-2 (an unchanged initial contract but changed renewal). Row0 renewal is outside those22 but already has known jitter. No rounded annual salary is inverted to recover a draw. Existing38 positive bonus relations remain downstream checks, not annual causes. Studio release-floor/premium roles are kept explicit and not numerically closed here.

H source additions authenticate against its accepted manifest hash from actual RESULT. A tick/aging/market additions authenticate accepted observed materialization receipt→bounded2,925,892-byte payload→selected physical source files. This authenticates selected historical roles only; no current full source freeze or fresh protected inventory claim. Input pins and all reviewed excerpts are retained. Root obtains independent source review next; no new measurement/execution is proposed by this proof.
''')
(OUT/'author-proof.py').write_bytes(Path(__file__).read_bytes())
allpins={p.name:{'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(OUT.iterdir()) if p.name!='SOURCE-PINS.json'};(OUT/'SOURCE-PINS.json').write_text(json.dumps(allpins,indent=2,sort_keys=True)+'\n');print(json.dumps({'path':str(OUT),'pinsSha256':hashlib.sha256((OUT/'SOURCE-PINS.json').read_bytes()).hexdigest(),'files':allpins,'missing23':missing}))
