import {openBridgeCheckpointStore,type BridgeCheckpointStore} from './bridge/runtime/checkpoint-store.ts';import {createBridgeRuntimeCoordinator,type BridgeRuntimeCoordinator} from './bridge/runtime/runtime-coordinator.ts';import {CAMPAIGN_LIBRARY_MAX_BYTES} from './bridge/runtime/campaign-library.ts';import {PROTOCOL_VERSION,SCHEMA_ID} from './bridge/protocol.ts';import {Session as Inspector} from 'node:inspector';import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';import {createHash} from 'node:crypto';import {performance} from 'node:perf_hooks';
const dir=process.argv[2],sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex'),assert=(x:unknown,m:string)=>{if(!x)throw Error(m)},source='/Users/bruce/The Movies - P12A Living Hollywood Unity/Evidence/P12A/early-2026-09-10T20-29-53-370Z/campaign-library-final.json',expected='66b79add059344d2704d6e27641ecf750f73acad8a358662c91a30eb5df50365';
const manifest=JSON.parse(readFileSync(dir+'/cpu-sources.json','utf8')),changes=()=>manifest.filter((r:any)=>sha(readFileSync(r.absolutePath))!==r.sha256).map((r:any)=>r.path);assert(changes().length===0,'Bound source changed');assert(!existsSync(dir+'/CPU-STARTED.json'),'Profile already exists');writeFileSync(dir+'/CPU-STARTED.json',JSON.stringify({pid:process.pid,at:new Date().toISOString()}),{flag:'wx',mode:0o600});
let store:BridgeCheckpointStore|null=null,runtime:BridgeRuntimeCoordinator|null=null,inspector:Inspector|null=null,profiling=false;
const report:any={order:'OPS-P12A-LIVING-HOLLYWOOD-20260910-05',kind:'single-complete-campaign-Save-cpu-profile',binding:JSON.parse(readFileSync(dir+'/cpu-binding.json','utf8')),startedAt:new Date().toISOString(),completed:false,errors:[],runtime:{node:process.version,executable:process.execPath,execArgv:process.execArgv,nodeOptionsPresent:!!process.env.NODE_OPTIONS},seed:{path:source,sha256:expected},qualifications:['One real production coordinator campaign Save, after protected fixed-seed load. Profiling starts immediately before campaign() and stops immediately after resolution. Copy, recovery, first snapshot, catalogue reads, hashing and cleanup are excluded.','V8 inspector sampling interval1000microseconds; instrumented wall timing is diagnostic and must not replace unprofiled n20 distribution. This samples this JavaScript isolate, not libuv compression-worker CPU; idle may include asynchronous compression wait.','Standalone private process, not HTTP/engine/Unity/main-thread-storage placement proof. No forced GC or shared-source changes. API-owned store closes normally; protected original is read/hash only.']};
const call=(method:string,params:any={})=>new Promise<any>((resolve,reject)=>inspector!.post(method as any,params,(error,result)=>error?reject(error):resolve(result)));
try{const bytes=readFileSync(source);assert(sha(bytes)===expected,'Wrong seed');report.seed.bytes=bytes.length;const root=dir+'/cpu-runtime';mkdirSync(root,{mode:0o700});store=await openBridgeCheckpointStore(root+'/bridge-runtime-v1.json',{runtimeRoot:root,maxBytes:CAMPAIGN_LIBRARY_MAX_BYTES});await store.writeAtomic(bytes.toString('utf8'));runtime=await createBridgeRuntimeCoordinator({store,campaigns:{durable:true,regime:'endowed'},fatal:e=>report.errors.push({fatal:true,message:String(e)})});const before=await runtime.read(s=>s.snapshot()),library=await runtime.campaignLibrary();assert(library&&before.gameWeek===8794&&before.stateDigest==='c0e93f9a727e82f68814d31862befcbc20ffa0ba16118f7bfe161f4d48897862','Wrong authority');
 const request:any={protocolVersion:PROTOCOL_VERSION,schemaId:SCHEMA_ID,commandId:'cpu-fixed-production-save-01',sessionId:library!.sessionId,expectedStateRevision:library!.stateRevision,expectedCatalogueRevision:library!.catalogueRevision,expectedActiveCampaignId:library!.activeCampaignId,type:'campaign',operation:'save',campaignId:null,label:null,overwriteCampaignId:null,confirmDestructive:false,unsavedDisposition:'requireClean'};
 inspector=new Inspector();inspector.connect();await call('Profiler.enable');await call('Profiler.setSamplingInterval',{interval:1000});await call('Profiler.start');profiling=true;
 const memoryBefore=process.memoryUsage(),start=performance.now(),response=await runtime.campaign(request),elapsedMs=performance.now()-start,memoryAfter=process.memoryUsage();const result=await call('Profiler.stop');profiling=false;
 writeFileSync(dir+'/campaign-save.cpuprofile',JSON.stringify(result.profile),{mode:0o600,flag:'wx'});assert(response.accepted&&response.gameWeek===before.gameWeek&&response.stateDigest===before.stateDigest,'Save failed/changed world');report.operation={elapsedMs,memoryBefore,memoryAfter,response,profileSha256:sha(readFileSync(dir+'/campaign-save.cpuprofile'))};report.completed=true;
}catch(error){report.errors.push({message:String(error),stack:String((error as Error).stack).split('\n').slice(0,6)});process.exitCode=1}
finally{try{if(profiling)await call('Profiler.stop');inspector?.disconnect()}catch(e){report.errors.push({profileCleanup:String(e)});report.completed=false}try{if(runtime)await runtime.close();else if(store)await store.close()}catch(e){report.errors.push({storeCleanup:String(e)});report.completed=false}report.sourceChanges=changes();report.protectedSeedUnchanged=sha(readFileSync(source))===expected;report.ownedLockAbsent=!existsSync(dir+'/cpu-runtime/bridge-runtime-v1.json.lock');if(report.errors.length||report.sourceChanges.length||!report.protectedSeedUnchanged||!report.ownedLockAbsent){report.completed=false;process.exitCode=1}report.finishedAt=new Date().toISOString();report.processMemory={...process.memoryUsage(),highWaterRssKiB:process.resourceUsage().maxRSS};writeFileSync(dir+'/cpu-report.json',JSON.stringify(report,null,2)+'\n',{mode:0o600});console.log(JSON.stringify({completed:report.completed,errors:report.errors,elapsedMs:report.operation?.elapsedMs,dir}));}
