import {openBridgeCheckpointStore,type BridgeCheckpointStore} from './bridge/runtime/checkpoint-store.ts';
import {createBridgeRuntimeCoordinator,type BridgeRuntimeCoordinator} from './bridge/runtime/runtime-coordinator.ts';
import {CAMPAIGN_LIBRARY_MAX_BYTES} from './bridge/runtime/campaign-library.ts';
import {PROTOCOL_VERSION,SCHEMA_ID} from './bridge/protocol.ts';
import {readFileSync,writeFileSync,mkdirSync,existsSync,chmodSync,lstatSync} from 'node:fs';
import {createHash} from 'node:crypto';import {performance} from 'node:perf_hooks';import {setImmediate as yieldNow} from 'node:timers/promises';import {cpus,totalmem,platform,release,arch} from 'node:os';import {getHeapStatistics} from 'node:v8';
const dir=process.argv[2],sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex'),assert=(x:unknown,m:string)=>{if(!x)throw Error(m)};
const source='/Users/bruce/The Movies - P12A Living Hollywood Unity/Evidence/P12A/early-2026-09-10T20-29-53-370Z/campaign-library-final.json',expected='66b79add059344d2704d6e27641ecf750f73acad8a358662c91a30eb5df50365';
const manifest=JSON.parse(readFileSync(dir+'/store-sources.json','utf8')), sourceChanges=()=>manifest.filter((r:any)=>sha(readFileSync(r.absolutePath))!==r.sha256).map((r:any)=>r.path);
assert(sourceChanges().length===0,'Compiled sources differ at entry');assert(!existsSync(dir+'/STORE-STARTED.json'),'Run already exists');
writeFileSync(dir+'/STORE-STARTED.json',JSON.stringify({pid:process.pid,at:new Date().toISOString()}),{flag:'wx',mode:0o600});
let stop=false,store:BridgeCheckpointStore|null=null,coordinator:BridgeRuntimeCoordinator|null=null,activePhase='setup';process.on('SIGTERM',()=>stop=true);process.on('SIGINT',()=>stop=true);
const report:any={order:'OPS-P12A-LIVING-HOLLYWOOD-20260910-05',kind:'production-store-coordinator-fixed-real-library',startedAt:new Date().toISOString(),completed:false,binding:JSON.parse(readFileSync(dir+'/store-binding.json','utf8')),seed:{path:source,sha256:expected},runtime:{node:process.version,executable:process.execPath,execArgv:process.execArgv,nodeOptionsPresent:!!process.env.NODE_OPTIONS},hardware:{platform:platform(),release:release(),arch:arch(),cpu:cpus()[0]?.model,logicalCpus:cpus().length,totalMemoryBytes:totalmem(),heapSizeLimit:getHeapStatistics().heap_size_limit},warmups:3,repetitions:20,percentile:'nearest-rank observed p95 (sorted index ceil(.95*n)-1), empirical n20; not a population guarantee',durableWrite:{warmups:[],samples:[]},loadReady:{warmups:[],samples:[]},campaignSave:{warmups:[],samples:[]},setup:[],errors:[],qualification:['Standalone isolated private benchmark process invoking unchanged production store/coordinator directly. No HTTP, worker-postMessage, Unity, native or engine-main placement claim.','Load-to-ready starts before production store ownership acquisition and includes coordinator recovery and first production snapshot, matching the worker ready computation except worker startup and message transport. Repeated in one process with ordinary OS page cache; not OS-cold launch.','Durable write phase includes production ownership checks, UTF-8 conversion/validation, file write+fsync, atomic replacement, directory fsync, and cleanup. Input serialization/compression is excluded because exact protected encoded UTF-8 is already available.','Complete campaign Save starts at coordinator.campaign and ends when its durable accepted response resolves. Includes proposal/fork/strict operations, production library encoding/compression and atomic write; excludes prior catalogue read, HTTP/client UI, and post-operation verification.','Every load/Save sample is reset to the identical protected real seed using production store.writeAtomic, then the owned store is closed through its API. This reset/setup, catalogue reads, validation hashes and file stats are excluded from timings and logged separately.','Each sample Save has a unique command ID; catalogue increments by one, active record revision increments by one. Runtime rollover may mint session UUIDs. Current world/week/digest and inactive record metadata must remain unchanged. No authoritative weekly advance or fabricated history.','No forced GC, heap flags, or cache clearing; per-sample heap/RSS before and after plus process high-water RSS are recorded. No claim these endpoint samples capture allocation volume or all RSS peaks.']};
const persist=()=>writeFileSync(dir+'/store-progress.json',JSON.stringify(report,null,2)+'\n',{mode:0o600});
const brief=(s:any)=>({sessionId:s.sessionId,stateRevision:s.stateRevision,gameWeek:s.gameWeek,stateDigest:s.stateDigest});
const measured=async(fn:()=>Promise<any>)=>{const before=process.memoryUsage(),start=performance.now(),value=await fn(),elapsedMs=performance.now()-start,after=process.memoryUsage();return {value,elapsedMs,heapBefore:before.heapUsed,heapAfter:after.heapUsed,rssBefore:before.rss,rssAfter:after.rss}};
const collect=(phase:any,i:number,m:any)=>{const {value,...record}=m;(i<0?phase.warmups:phase.samples).push({sample:i<0?i+3:i,...record});persist();console.log(JSON.stringify({phase:activePhase,sample:i,elapsedMs:m.elapsedMs}));};
const checkStop=()=>{if(stop||existsSync(dir+'/PAUSE'))throw Error('Interrupted at safe sample boundary')};
const summary=(phase:any)=>{const v=phase.samples.map((r:any)=>r.elapsedMs).sort((a:number,b:number)=>a-b);return {n:v.length,medianMs:(v[(v.length-1)>>1]+v[v.length>>1])/2,p95Ms:v[Math.ceil(.95*v.length)-1],maxMs:v.at(-1),minMs:v[0]}};
const root=dir+'/runtime',checkpoint=root+'/bridge-runtime-v1.json';
const openStore=()=>openBridgeCheckpointStore(checkpoint,{runtimeRoot:root,maxBytes:CAMPAIGN_LIBRARY_MAX_BYTES});
try{
 const raw=readFileSync(source);assert(sha(raw)===expected,'Protected seed SHA differs');assert(!lstatSync(source).isSymbolicLink(),'Seed symlink');const seed=raw.toString('utf8');report.seed.bytes=raw.length;mkdirSync(root,{mode:0o700});store=await openStore();await store.writeAtomic(seed);
 activePhase='production-durable-write-identical-encoded-library';
 for(let i=-3;i<20;i++){checkStop();const m=await measured(()=>store!.writeAtomic(seed));assert(sha(readFileSync(checkpoint))===expected,'Durable bytes differ');collect(report.durableWrite,i,m);await yieldNow()}
 await store.close();store=null;
 let baseline:any=null;
 for(let i=-3;i<20;i++){
  checkStop();const setup=await measured(async()=>{store=await openStore();await store.writeAtomic(seed);assert(sha(readFileSync(checkpoint))===expected,'Reset differs');await store.close();store=null});report.setup.push({sample:i,kind:'restore-identical-encoded-seed',elapsedMs:setup.elapsedMs});
  activePhase='production-load-to-first-ready-snapshot';
  const loading=await measured(async()=>{store=await openStore();coordinator=await createBridgeRuntimeCoordinator({store,campaigns:{durable:true,regime:'endowed'},fatal:error=>report.errors.push({fatal:true,message:String(error)})});return coordinator.read(s=>s.snapshot())});
  const snap=brief(loading.value);assert(snap.gameWeek===8794&&snap.stateDigest==='c0e93f9a727e82f68814d31862befcbc20ffa0ba16118f7bfe161f4d48897862','Wrong loaded authority');
  const catalogue=await coordinator!.campaignLibrary();assert(catalogue!==null,'Missing library');baseline??={snapshot:snap,catalogue};assert(JSON.stringify(catalogue)===JSON.stringify(baseline.catalogue),'Fixed library catalogue changed');loading.value=null;
  collect(report.loadReady,i,{...loading,authority:snap,checkpointChangedOnLoad:sha(readFileSync(checkpoint))!==expected});
  activePhase='complete-production-campaign-Save';
  const request:any={protocolVersion:PROTOCOL_VERSION,schemaId:SCHEMA_ID,commandId:'fixed-production-save-'+String(i+3).padStart(2,'0'),sessionId:catalogue!.sessionId,expectedStateRevision:catalogue!.stateRevision,expectedCatalogueRevision:catalogue!.catalogueRevision,expectedActiveCampaignId:catalogue!.activeCampaignId,type:'campaign',operation:'save',campaignId:null,label:null,overwriteCampaignId:null,confirmDestructive:false,unsavedDisposition:'requireClean'};
  const saved=await measured(()=>coordinator!.campaign(request)),response=saved.value;assert(response.accepted===true,'Save rejected: '+response.reasonCode);assert(response.stateDigest===snap.stateDigest&&response.gameWeek===snap.gameWeek,'Save changed world');assert(response.catalogueRevision===catalogue!.catalogueRevision+1,'Wrong catalogue increment');
  const after=await coordinator!.campaignLibrary();assert(after!.activeCampaignId===catalogue!.activeCampaignId&&!after!.dirty,'Active save did not publish');
  for(const before of catalogue!.campaigns){const row=after!.campaigns.find(x=>x.id===before.id);assert(row&&JSON.stringify({...row,revision:before.revision})===JSON.stringify(before),'Campaign metadata changed unexpectedly');assert(row!.revision===before.revision+(before.id===catalogue!.activeCampaignId?1:0),'Record revision changed incorrectly')}
  const st=lstatSync(checkpoint);collect(report.campaignSave,i,{...saved,response:{...brief(response),catalogueRevision:response.catalogueRevision,accepted:response.accepted},checkpoint:{bytes:st.size,sha256:sha(readFileSync(checkpoint)),mode:st.mode&0o777}});saved.value=null;
  await coordinator!.close();coordinator=null;store=null;assert(!existsSync(checkpoint+'.lock'),'Owned API close left lock');await yieldNow();
 }
 report.baseline=baseline;report.completed=true;
}catch(error){report.errors.push({phase:activePhase,message:(error as Error).message,stack:String((error as Error).stack).split('\n').slice(0,6)});process.exitCode=1}
finally{
 try{if(coordinator)await coordinator.close();else if(store)await store.close()}catch(error){report.errors.push({cleanup:true,message:String(error)});report.completed=false;process.exitCode=1}
 report.sourceChanges=sourceChanges();report.protectedSeedUnchanged=sha(readFileSync(source))===expected;report.ownedLockAbsent=!existsSync(checkpoint+'.lock');if(report.sourceChanges.length||!report.protectedSeedUnchanged||!report.ownedLockAbsent){report.completed=false;process.exitCode=1}
 for(const name of ['durableWrite','loadReady','campaignSave'])report[name].summary=summary(report[name]);report.finishedAt=new Date().toISOString();report.processMemory={...process.memoryUsage(),highWaterRssKiB:process.resourceUsage().maxRSS};persist();writeFileSync(dir+'/store-report.json',JSON.stringify(report,null,2)+'\n',{mode:0o600});console.log(JSON.stringify({completed:report.completed,counts:Object.fromEntries(['durableWrite','loadReady','campaignSave'].map(n=>[n,report[n].samples.length])),errors:report.errors,dir}));
}
