"""Decisions for the measured sites that the S1/S2 rules do not cover. Key: the innermost tests frame (file:line)."""
from msgs import *
S8E = 'rename validateSaveV44( to validateSaveV45( at this call and in the import; keep the pattern'
def s8(expected_src):
    return dict(cls='S8', edit=S8E, expected=expected_src, status='measure',
                note='M2 stops at the frozen V44 version check; after the rename validateSaveV45 hands the frozen V44 chain the tampered state, so the pinned guard is expected to fire as under Save44. The dry run message probe decides.')
def s3(edit, note=''):
    return dict(cls='S3', edit=edit, expected=E_S3, status='certain',
                note=('the stamp 45 is now the live version, so validateSaveV45 admits a live save stamped 45 or refuses an older one at its root check (' + SRC_ROOTMISSING + '). ' + note).strip())
SPECIAL = {
 # ---- S5 whole-state comparisons ----
 'tests/bridge-p14c3-promise-digest-continuity.test.ts:165': dict(cls='S5',
   edit='expectedOld (:164) gains the four P15 roots through a per-file helper withEmptyP15Roots beside withEmptyCompetitionsAndRomance, built from old.state.market.tick; :174 toBe(44) -> toBe(45) (S2, masked)',
   expected='canonicalJson equality holds: the migrated state differs from old.state only by known roots, now including powerRanking {version 1, recordedFromWeek W, snapshots []}, p15Sequence {version 1, next 1}, sharedMarket {version 1, recordedFromWeek W, assessments []}, campaignLegacy {version 1, recordedFromWeek W, official null, endOfRun null}, W = the slot week (208, 207)',
   status='measure', note='measured diff starts at the new key campaignLegacy; ' + SRC_ROOTS),
 'tests/p14b4-save-v30-compatibility.test.ts:216': dict(cls='S5',
   edit='the expected state at :216-219 gains the four P15 roots at migrated.state.market.tick through a per-file helper withEmptyP15Roots; :252 toBe(44) -> toBe(45) (S2)',
   expected='toEqual holds for all 21 cases: lifted differs from migrated only by the listed lifts plus the four empty P15 roots at the input week',
   status='measure', note=SRC_ROOTS),
 'tests/p14b3-rule-revision.test.ts:174': dict(cls='S5',
   edit='the expected state at :174 gains the four P15 roots at parsedRaw.state.market.tick through a per-file helper withEmptyP15Roots',
   expected='toEqual holds: the governed export differs from the raw V29 input only by the listed lifts plus the four empty P15 roots', status='measure', note=SRC_ROOTS),
 'tests/p14bf2-acting-discipline.test.ts:366': dict(cls='S5',
   edit='the expected state at :366 gains the four P15 roots at parsedRaw.state.market.tick through a per-file helper withEmptyP15Roots',
   expected='toEqual holds with the four empty P15 roots added', status='measure', note=SRC_ROOTS),
 'tests/p14p4p5-casting-reservation.test.ts:209': dict(cls='S5',
   edit='the expected state at :209 gains the four P15 roots at old.state.market.tick (45) through a per-file helper withEmptyP15Roots',
   expected='toEqual holds: 44 keys against 44 (the four P15 roots at week 45, nothing recorded)', status='measure', note='measured: received 44 keys, expected 40; ' + SRC_ROOTS),
 'tests/p14p4p5-delayed-retirement.test.ts:189': dict(cls='S5',
   edit='the expected state at :189 gains the four P15 roots at old.state.market.tick (45) through a per-file helper withEmptyP15Roots',
   expected='toEqual holds with the four empty P15 roots at week 45', status='measure', note='measured: received 44 keys, expected 40; ' + SRC_ROOTS),
 'tests/p14p4p5-queued-project-outcome.test.ts:186': dict(cls='S5',
   edit='the expected state at :186 gains the four P15 roots at old.state.market.tick (45) through a per-file helper withEmptyP15Roots',
   expected='toEqual holds with the four empty P15 roots at week 45', status='measure', note='measured: received 44 keys, expected 40; ' + SRC_ROOTS),
 'tests/p14p4p5-scenery-capacity.test.ts:202': dict(cls='S5',
   edit='the expected state at :202 gains the four P15 roots at old.state.market.tick (45) through a per-file helper withEmptyP15Roots',
   expected='toEqual holds with the four empty P15 roots at week 45', status='measure', note='measured: received 44 keys, expected 40; ' + SRC_ROOTS),
 'tests/p14d1-rival-shelving.test.ts:618': dict(cls='S5',
   edit='week-93 control (the 1358-F12 form): before the comparison, assert the candidate holds no shared-market assessment and an unfrozen Legacy and that its archive passes validatePowerRankingArchive and validateP15Allocator; then take the four P15 roots out of the candidate as :616 takes slice B out; the genuine side stays at its V44 lift (:569)',
   expected='canonical JSON equality holds outside the P15 roots and Save43/Save44 roots; receipts identical (:619)',
   status='ruling', note='a genuine Save42 input cannot hold a Power Ranking archive, and the route records quarters 13 to 91 by week 93. Needs a parent ruling like 1358-F12 ruling 7. Measured diff starts at the new key campaignLegacy.'),
 # ---- S5 hand lifts ----
 'tests/p14c1-materialized-aging.test.ts:190': dict(cls='S5', edit='liftForTick (:178) gains one governed step, SaveModule.convertV44ToV45(...), with a comment in the 1358-N form; this one edit clears all 17 rows of the file that tick a lifted state',
   expected='tick() accepts the lifted state; each leaf proceeds to its own assertions', status='certain', note='hand lift stopped at V44, so the tick refuses at its first industry week (1361-D2 F7); ' + SRC_MARKET),
 'tests/p14c1-materialized-aging.test.ts:440': dict(cls='S5', edit='same edit as :190 (liftForTick at :178)', expected='tick() accepts the lifted state', status='certain', note=SRC_MARKET),
 'tests/p14c1-materialized-aging.test.ts:693': dict(cls='S5', edit='same edit as :190 (liftForTick at :178)', expected='tick() accepts the lifted state', status='certain', note=SRC_MARKET),
 'tests/p14c1-materialized-aging.test.ts:1017': dict(cls='S5', edit='same edit as :190 (liftForTick at :178); `constructed` spreads the lifted state, so it then carries all four roots',
   expected='no throw: tick(constructed) runs', status='certain', note=SRC_MARKET),
 'tests/p14b9-save-v42.test.ts:213': dict(cls='S5', edit='the hand lift at :192 gains mods.convertV44ToV45 (with a typed member beside :175-177); :214 toBe(44) -> 45 (S2); :176/:215 validateSaveV44 member -> validateSaveV45 (S1); :177/:223 add convertV45ToV44 innermost (S4)',
   expected='makeSave(greenlit) writes a V45 save; :223 then refuses at the pinned competitions-log guard, because the lifted state was never ticked and its archive is empty',
   status='certain', note='measured: ' + SRC_ROOTMISSING + ' (the new validator refuses first on a state lifted only to V44)'),
 # ---- S7 shape controls and older-era hand projections ----
 'tests/contracts/_v14Contract.ts:528': dict(cls='S7', edit='projectToV13State (:377-509) drops powerRanking, p15Sequence, sharedMarket and campaignLegacy, each under the file\'s own emptiness precondition (throw "V13 twin cannot discard P15 authority" if snapshots or assessments are non-empty, the Legacy holds official or endOfRun, or p15Sequence.next is not 1)',
   expected='v13TwinOf validates at V13; the 25 v14-migration contract leaves reach their own assertions', status='measure',
   note='measured refusal inside the contract message: validateSaveV12: state has unknown field "powerRanking" (' + SRC_V12KEYS + '). The cells are founded studios without an industry, so the roots are expected empty.'),
 'tests/facility-move-demolish.test.ts:876': dict(cls='S7', edit='forgedV11 (the :8xx block) deletes the four P15 roots, each removed only while empty, beside the firstTakeSubjects deletion at :868-869',
   expected='/SaveFileV13 facility demolition authority|facilityDemolitionRefund/ (src/core/save.ts:916)', status='certain',
   note='measured: validateSaveV11: state has unknown field "campaignLegacy" (' + SRC_V11KEYS + ')'),
 'tests/p13b-r07-save-v25.test.ts:248': dict(cls='S7', edit='asV25Envelope (:149) deletes the four P15 roots, each removed only while empty, beside the relationships and careerLifecycle deletions',
   expected='migrateToV25 validates the reconstructed V25 envelope', status='certain',
   note='measured: validateSaveV25 frozen chain ending validateSaveV12: state has unknown field "powerRanking" (src/core/save.ts:8613, :4185)'),
 'tests/p13b-r07-save-v25.test.ts:258': dict(cls='S7', edit='same edit as :248 (asV25Envelope)', expected='migrateToV25 validates; :259-263 then reach their /cannot downgrade/i refusals on the V25 envelope', status='certain',
   note='measured as :248'),
 'tests/p14c2s-scientist-retirement.test.ts:346': dict(cls='S7', edit='the reader-only V34-V36 relabel (:300-342) also deletes the four P15 roots, with a comment in the 1358-N S7 form',
   expected='no throw for the V34, V35 and V36 whole-envelope controls; :347 then refuses /Scientist record/', status='certain',
   note='measured: validateSaveV34 frozen chain ending validateSaveV12: state has unknown field "powerRanking" (src/core/save.ts:9958, :4185)'),
 # ---- S10 ----
 'tests/p14b5-relationships.test.ts:626': dict(cls='S10', edit='bytes() (:272) extends its guard-before-strip form (1332-A :84-90; 1344-F4 ruling 2) to the four P15 roots: assert them with their own validators (validatePowerRankingArchive, validateSharedMarketRoot, validateCampaignLegacy, validateP15Allocator) before the strip drops them; FROZEN.postTakeDigestStripped (:161) does not move',
   expected="sha(bytes(after)) = '9702aa6869cf80f82d5133f68137427a0ed44c07ce987e8fe2be66bbb60f3d78' (unchanged)", status='measure',
   note="measured received 80fe2347e47678fefdf4b175f0b48046a11a97828d93aa4b3056ca4de8490c87: the live bytes now carry the four roots (" + SRC_ROOTS + "). Probe before writing: compute the stripped digest on the candidate."),
 'tests/p14c3-save-v38.test.ts:105': dict(cls='S10', edit='none: retained 1358-I identity (C20); its primary embeds the live version', expected='still fails, primary "expected \'{"broadcastCache":[],"saveVersion":45…\' to be \'{"broadcastCache":[],"saveVersion":38…\'"; the gate compare attributes the change (1358-F9 ruling 7)', status='certain', note='CHANGED in M2 by the version only'),
 # ---- S2 special ----
 'tests/bridge-process-restart.test.ts:897': dict(cls='S2', edit=':797 and :799 toBe(44) -> toBe(45); the frame :897 rethrows the assertion with the child bridge logs', expected=E_S2, status='certain', note='frames: :897 then :797'),
 'tests/bridge-runtime-checkpoint.test.ts:439': dict(cls='S2', edit='/canonical V44 save bytes exactly/ -> /canonical V45 save bytes exactly/ (1358-F10 ruling 7 labels this S2)', expected='checkpoint.currentSaveJson: must preserve the canonical V45 save bytes exactly (' + SRC_BRIDGE_CANON + ')', status='certain', note=''),
 # ---- S3 sentinels ----
 'tests/construction-save-v11.test.ts:553': s3('stamp 45 -> 46 at :553; /unknown saveVersion 45.*versions 1 through 44 only/ -> /unknown saveVersion 46.*versions 1 through 45 only/ at :554'),
 'tests/p13b-s2-save-v22.test.ts:214': s3('stamp 45 -> 46; /versions 1 through 44 only/ -> /versions 1 through 45 only/; title :211 45 -> 46 (T)'),
 'tests/p13b-s3-save-v23.test.ts:126': s3('stamp 45 -> 46 at :125; /versions 1 through 44 only/ -> 45 at :126; title :124 45 -> 46 (T)'),
 'tests/p13b-s5-save-v24.test.ts:215': s3('stamp 45 -> 46 at :214; "1 through 44" -> "1 through 45" at :215; title :213 (T)'),
 'tests/p13b-r07-save-v25.test.ts:275': s3('stamp 45 -> 46 at :274; "1 through 44" -> "1 through 45" at :275; title :273 (T)'),
 'tests/p13b-s6-save-v26.test.ts:225': s3('stamp 45 -> 46 at :224; "1 through 44" -> "1 through 45" at :225; title :221 (T)'),
 'tests/p13b-s8-save-v27.test.ts:236': s3('stamp 45 -> 46 at :235; "1 through 44" -> "1 through 45" at :236; title :232 (T)'),
 'tests/p14a1-save-v28.test.ts:256': s3('stamp 45 -> 46 at :255; "1 through 44" -> "1 through 45" at :256; title :252 (T)'),
 'tests/p14b1-save-v29.test.ts:206': s3('stamp 45 -> 46 at :205; "1 through 44" -> "1 through 45" at :206; title :202 (T)'),
 'tests/save.test.ts:455': s3('stamp 45 -> 46 at :455; "1 through 44" -> "1 through 45" at :456; title :453 (T); :458 then runs (S9 measure)'),
 'tests/property-state-v13.test.ts:943': s3('stamp 45 -> 46 at :943; /unknown saveVersion 45.*versions 1 through 44 only/ -> 46/45 at :944'),
 'tests/d17a-adv-migration.test.ts:274': s3('stamp 45 -> 46 and /unknown saveVersion 45/ -> /unknown saveVersion 46/'),
 'tests/d17b-save-v7.test.ts:163': s3('stamp 45 -> 46 and /unknown saveVersion 45/ -> /unknown saveVersion 46/'),
 'tests/script-projects-save-v9.test.ts:415': s3('stamps 45 -> 46 at :415 and :418; /unknown saveVersion 45/ -> 46 at :416; "1 through 44" -> "1 through 45" at :419'),
 'tests/save.test.ts:289': s3('stamp 45 -> 46 at :288; pin the bare .toThrow() at :289 as /unknown saveVersion 46/ (1358-N S3 named this bare leaf)', 'measured: no throw, because a live save stamped 45 is valid'),
 'tests/p14b9-save-v42.test.ts:233': dict(cls='S3', edit='/1 through 44/ -> /1 through 45/; title :232 (T)', expected='validateSave: unknown saveVersion 999 (this build handles versions 1 through 45 only) (' + SRC_DISPATCH + ')', status='certain', note='measured exactly that message'),
 # ---- S8 ----
 'tests/cash-ledger-checkpoint-v11.test.ts:287': s8('cash-ledger checkpoint must encode a genuine historical reconciliation boundary (src/core/construction.ts:445)'),
 'tests/cash-ledger-checkpoint-v11.test.ts:461': s8('studio cash must equal the historical checkpoint plus the ordered post-checkpoint ledger (src/core/construction.ts:463)'),
 'tests/construction-core.test.ts:497': s8('cannot reserve the Annex before Week 13 (src/core/construction.ts:340-360 or src/core/placement.ts:2271)'),
 'tests/construction-core.test.ts:566': s8('placed-facility reservation disagrees with its authoritative greenlight week (src/core/placement.ts:2238)'),
 'tests/construction-save-v11.test.ts:514': s8('canonical Annex id … collides with persisted production history (src/core/construction.ts:251 or src/core/placement.ts:2015)'),
 'tests/legacy-parcel-ground.test.ts:365': s8("placed facility … stands on ground reserved for the studio's Annex contract (src/core/placement.ts:2066)"),
 'tests/legacy-parcel-ground.test.ts:404': s8("reserved for the studio's Annex (src/core/placement.ts:2066)"),
 'tests/p06a-w1-release-authority.test.ts:459': s8('commitment … carries foreign identity (src/core/releaseAuthority.ts:172)'),
 'tests/p13a-technology-milestones.test.ts:74': s8('technology milestone is not an exact catalogue boundary (src/core/studioHistory.ts:357)'),
 'tests/property-state-v13.test.ts:799': s8('state is missing required field "property" (the frozen chain\'s required-key check, e.g. src/core/save.ts:3931)'),
 'tests/property-state-v13.test.ts:868': s8('property road 0 is not a well-formed rectangle inside the property bounds (src/core/placement.ts:1651)'),
 'tests/property-state-v13.test.ts:880': s8('placed facility 1 overlaps property structure "theater" (src/core/placement.ts:2040)'),
 'tests/p14b5-relationships.test.ts:1299': s8('each family 10 case\'s own validateRelationshipsRoot refusal at era 44 (src/core/relationships.ts:666-), as under Save44; :1305 keeps validateRelationshipsRoot(save.state, 44)'),
 'tests/p14b5-relationships.test.ts:1321': s8('the missing relationships root, refused through validateSaveV44(stripped) (src/core/relationships.ts:666-)'),
 # ---- S1 special ----
 'tests/contracts/studio-events.contract.test.ts:212': dict(cls='S1', edit="the by-name lookup at :129 'validateSaveV44' -> 'validateSaveV45'", expected=E_S1, status='certain', note='validateAtOwningBoundary validates a forged live save (makeSave(managed), :132)'),
 'tests/contracts/studio-events.contract.test.ts:240': dict(cls='S1', edit="same edit as :212 (by-name lookup at :129)", expected=E_S1, status='certain', note=''),
 'tests/contracts/studio-events.contract.test.ts:332': dict(cls='S1', edit="same edit as :212 (by-name lookup at :129)", expected=E_S1, status='certain', note=''),
 # ---- S4 chains that must succeed ----
 'tests/contracts/v14-boundary-guards.contract.test.ts:63': dict(cls='S4', edit='insert convertV45ToV44 innermost: convertV44ToV43(convertV45ToV44(makeSave(state))); add it to the import (:34); this clears the suite-level failure',
   expected='the chain succeeds (operationsStudio has no industry, so every P15 root is empty); the file then runs its leaves, including :322 (S3) and the loose /cannot downgrade/ pins at :211, :250, :275, :300', status='measure',
   note='suite-level row; also TS2345 at (63,132)'),
 'tests/p06a-w1-release-authority.test.ts:406': dict(cls='S4', edit='insert convertV45ToV44 innermost; add it to the import (:32)',
   expected='the chain succeeds (a founded studio with no industry; M2 already shows :447 reaching its V39 guard through the production chain)', status='measure', note='TS2345 at (406,136)'),
 'tests/save.test.ts:370': dict(cls='S4', edit='insert convertV45ToV44 innermost; add it to the import (:35)', expected='the chain succeeds (contendedStudio has no industry)', status='measure', note='TS2345 at (370,136)'),
 'tests/save.test.ts:419': dict(cls='S4', edit='insert convertV45ToV44 innermost', expected='the chain succeeds (as :370)', status='measure', note='TS2345 at (419,136)'),
 'tests/p14c3-promise-digest-continuity.test.ts:279': dict(cls='S4', edit='insert convertV45ToV44 innermost; add it to the import (:14)', expected='exportSave of the chain equals the genuine raw bytes: `current` migrates genuine bytes with no tick, so its roots are empty and drop', status='measure', note='TS2345 at (279,135); 1358-N recorded no S9 risk here'),
 'tests/helpers/p14c2b-fixtures.ts:69': dict(cls='S4', edit='liveEnvelopeV36: insert convertV45ToV44 innermost; add it to the import (:23)',
   expected='p14c2b-save-v36:64 (`live`, never ticked) succeeds; :83 and :98 meet the S9 question (their states tick from week 52 past 65, 78 and 91)', status='measure', note='TS2345 at (69,138) in all three gates'),
 'tests/p12-starting-world.test.ts:55': dict(cls='S4', edit='insert convertV45ToV44 innermost; add it to the import (:2)',
   expected='/^makeSaveV18: cannot downgrade or discard profession transition, industry retirement or entrant authority$/ (src/core/professionHistory.ts:67), unchanged: the week-0 state holds no quarter', status='measure', note='S9 site; TS2345 at (55,92)'),
 # ---- S9 measured ----
 'tests/p13b-s8-save-v27.test.ts:206': dict(cls='S9', edit='the S9 form: the pin names the measured first guard, /^migrateToV44: cannot downgrade or discard a recorded Power Ranking quarter$/, and the comment records the masking and names p14b10-save-v44:356 as the romance guard\'s own-era cover; :194 takes the same form (masked by :187)',
   expected=P15GUARD + ' (' + SRC_P15GUARD + ')', status='certain', note='measured in M2 through the production chain migrateToV26'),
 'tests/p14c2b-save-v36.test.ts:83': dict(cls='S9', edit='after H\'s S4 insert in liveEnvelopeV36, pin the measured first guard (expected the P15 refusal) in the S9 form', expected=P15GUARD + ' (predicted: advanceTo 92/98 from the week-52 capture records quarters 65, 78, 91)', status='measure', note='M2 stops at H\'s helper chain (validateSaveV44: expected version 44)'),
 'tests/p14c2b-save-v36.test.ts:98': dict(cls='S9', edit='as :83', expected=P15GUARD + ' (predicted, as :83)', status='measure', note='as :83'),
 'tests/p14r3-save-v41.test.ts:381': dict(cls='S9', edit='insert convertV45ToV44 innermost (S4); then pin the measured first guard in the S9 form', expected=P15GUARD + ' (predicted: lawfulTerminatedSave ticks p13aGeneratedStudio to week 23, past quarter 13)', status='measure', note=''),
 'tests/p14c3-transitions.test.ts:207': dict(cls='S9', edit='H moves envelope38 (p14c3-fixtures.ts:136) first; then insert convertV45ToV44 innermost here and at :175 (S4) and pin the measured first guard in the S9 form', expected='measured after H and the insert: the P15 refusal if `reopened` crossed a quarter since its migration, else the pinned V37 guard', status='measure', note='M2 message comes from the H pin inside the callback'),
 # ---- out of sweep ----
 'tests/hygiene.test.ts:45': dict(cls='X', edit='none in the sweep: the offender is the P15 RED file tests/p15c2-campaign-legacy-integration.test.ts, whose comment at :79 holds the literal "Math.random"', expected='a parent ruling: a one-word comment edit in the RED file by its owner, outside the sweep, or a declared exception', status='ruling', note='not Save45 fallout: it fails at HEAD since the 1360 RED landing'),
 'tests/bridge-supervisor.test.ts:110': dict(cls='ENV', edit='none', expected='environment row (1320-X): re-measured on the recorded gate on a quiet machine', status='certain', note='Fake Unity did not report …'),
 'tests/r3n1-stale-schedule-take-02.test.ts:100': dict(cls='ENV', edit='none', expected='retained 1358-I row, ENOENT at the repository path on the recorded gate', status='certain', note='CHANGED in M2 by the scratch path only'),
 'tests/r3n1-stale-schedule-take-02p31.test.ts:107': dict(cls='ENV', edit='none', expected='retained 1358-I row, ENOENT at the repository path on the recorded gate', status='certain', note='CHANGED in M2 by the scratch path only'),
 'tests/r3n1-stale-schedule-take-02p32.test.ts:98': dict(cls='ENV', edit='none', expected='retained 1358-I row, ENOENT at the repository path on the recorded gate', status='certain', note='CHANGED in M2 by the scratch path only'),
}
