import {tick} from './src/core/tick.ts';
import {makeSave,exportCurrentState,importSave} from './src/core/save.ts';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {setImmediate as yieldNow} from 'node:timers/promises';
import {cpus,totalmem,platform,release,arch} from 'node:os';
import {getHeapStatistics} from 'node:v8';
const dir='/tmp/p12a-core-resume-t7c16t09',prior='/tmp/p12a-engineering-8788-P6KEMm';
const sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
const assert=(yes:boolean,message:string)=>{if(!yes)throw new Error(message)};
const old=JSON.parse(readFileSync(prior+'/report.json','utf8'));
const report:any={purpose:'Independent CURRENT pure-core continuation from authorized all-nine week2548 checkpoint through6240 additional ordinary ticks; not bridge/native acceptance',start:new Date().toISOString(),commit:'6827293985a1375e8cefed745fbc4227a01aeb53',driver:'importSave(existing V19).state; tick(state,{develop:true}); no player actions',applicability:'Old fresh-world0→2548 trace remains separate. This run certifies current-source2548→8788 continuation, existing saved-world import, exact prior final comparison, and reload/next-tick equivalence only.',runtime:process.version,execArgv:process.execArgv,hardware:{platform:platform(),release:release(),arch:arch(),cpu:cpus()[0]?.model,logicalCpus:cpus().length,totalMemoryBytes:totalmem(),heapSizeLimit:getHeapStatistics().heap_size_limit},validations:[],checkpoints:[],checks:[],errors:[],ticks:{count:0,totalMs:0,maxMs:0,over2ms:0,over10ms:0},completed:false};
let state:any,rng:any,stopped=false;process.on('SIGTERM',()=>{stopped=true});process.on('SIGINT',()=>{stopped=true});
const persist=()=>writeFileSync(dir+'/report-progress.json',JSON.stringify(report,null,2),{mode:0o600});
const summary=(s:any)=>({week:s.market.tick,studios:s.hollywood.businesses.length,people:s.talent.length,films:s.hollywood.films.length,liveFilms:s.hollywood.films.filter((f:any)=>f.provenance==='simulation/v1').length,authoredFilms:s.hollywood.films.filter((f:any)=>f.provenance!=='simulation/v1').length,careerEvents:s.hollywood.careerEvents.length,employmentIntervals:s.hollywood.employment.length,currentEmployment:s.hollywood.activeEmploymentOrdinals.length,receipts:s.hollywood.receipts.length,concepts:s.hollywood.concepts.length,playerRngUnchanged:s.rngState===rng,rngState:s.rngState,seed:s.seed,worldId:s.hollywood.worldId,byBusiness:s.hollywood.businesses.map((b:any)=>({studioId:b.studioId,name:s.hollywood.identities.find((i:any)=>i.studioId===b.studioId).name,films:s.hollywood.films.filter((f:any)=>f.studioId===b.studioId&&f.provenance==='simulation/v1').length,cash:b.account.cash,finiteCash:Number.isFinite(b.account.cash),activeEmployment:s.hollywood.activeEmploymentOrdinals.filter((i:number)=>s.hollywood.employment[i].studioId===b.studioId).length}))});
const validate=()=>{const started=performance.now();makeSave(state);report.validations.push({week:state.market.tick,ms:performance.now()-started});};
const differences=(a:any,b:any,path='$',rows:any[]=[]):any[]=>{if(Object.is(a,b)||rows.length>=12)return rows;if(a===null||b===null||typeof a!=='object'||typeof b!=='object'){rows.push({path,old:a,current:b});return rows}const keys=new Set([...Object.keys(a),...Object.keys(b)]);for(const k of keys){if(rows.length>=12)break;if(!Object.hasOwn(a,k)||!Object.hasOwn(b,k))rows.push({path:path+'.'+k,oldPresent:Object.hasOwn(a,k),currentPresent:Object.hasOwn(b,k)});else differences(a[k],b[k],path+'.'+k,rows)}return rows};
function checkpoint(name:string,saveArtifact=false){const started=performance.now(),before=process.memoryUsage(),json=exportCurrentState(state),exportMs=performance.now()-started;const reloadStarted=performance.now(),imported=importSave(json);assert(imported.saveVersion===19,'Checkpoint changed save version');const reloaded=imported.state,reloadedBytes=exportCurrentState(reloaded);assert(reloadedBytes===json,'Reload canonical bytes changed at '+state.market.tick);const directNext=tick(state,{develop:true}),reloadedNext=tick(reloaded,{develop:true}),directNextBytes=exportCurrentState(directNext),reloadedNextBytes=exportCurrentState(reloadedNext);assert(directNextBytes===reloadedNextBytes,'Reload changed next ordinary tick at '+state.market.tick);assert(directNext.rngState===rng&&reloadedNext.rngState===rng,'Player RNG changed across reload-nexttick');const row={name,...summary(state),saveBytes:Buffer.byteLength(json),saveSha256:sha(json),exportMs,roundTripAndNextTickMs:performance.now()-reloadStarted,exactRoundTrip:true,exactNextTick:true,nextTickSha256:sha(directNextBytes),memoryBefore:before,memoryAfter:process.memoryUsage()};report.checkpoints.push(row);if(saveArtifact)writeFileSync(dir+'/week-'+state.market.tick+'.save.json',json,{mode:0o600});console.log(JSON.stringify({checkpoint:state.market.tick,bytes:row.saveBytes,sha256:row.saveSha256,exactNextTick:true}));persist();return json;}
const tickTimes:number[]=[];
try{
 const input=readFileSync(prior+'/week-2548.save.json','utf8'),inputStarted=performance.now(),loaded=importSave(input);assert(loaded.saveVersion===19,'Input is not exact current V19');state=loaded.state;rng=state.rngState;assert(state.market.tick===2548&&state.hollywood.businesses.length===9,'Input must be exact week2548 all-nine world');assert(state.seed===old.seed,'Seed differs from prior report');assert(exportCurrentState(state)===input,'Current importer/exporter changed exact input bytes');report.input={path:prior+'/week-2548.save.json',sha256:sha(input),bytes:Buffer.byteLength(input),strictImportAndCanonicalRoundTripMs:performance.now()-inputStarted,...summary(state)};const oldStart=old.checkpoints.find((p:any)=>p.week===2548);assert(report.input.sha256===oldStart.saveSha256,'Input no longer matches original bound report');validate();checkpoint('current-source input reload proof');
 while(state.market.tick<8788){if(stopped)throw new Error('Interrupted for native priority or explicit stop');const before=state.market.tick,started=performance.now();state=tick(state,{develop:true});const ms=performance.now()-started;tickTimes.push(ms);report.ticks.count++;report.ticks.totalMs+=ms;report.ticks.maxMs=Math.max(report.ticks.maxMs,ms);if(ms>2)report.ticks.over2ms++;if(ms>10)report.ticks.over10ms++;assert(state.market.tick===before+1,'Ordinary tick did not advance exactly one week');assert(state.rngState===rng,'Player RNG changed at '+state.market.tick);assert(state.hollywood.businesses.length===9,'All-nine business authority changed at '+state.market.tick);for(const b of state.hollywood.businesses)assert(Number.isFinite(b.account.cash),'Nonfinite business cash');
  if(state.market.tick%52===0){validate();await yieldNow();}
  if(state.market.tick===5668)checkpoint('midpoint reload proof');
  if((state.market.tick-2548)%520===0){console.log(JSON.stringify({progressWeek:state.market.tick,ticks:report.ticks.count,validations:report.validations.length,tickMs:report.ticks.totalMs}));persist();}
 }
 assert(report.ticks.count===6240,'Wrong continuation tick count');const finalBytes=checkpoint('final current-source reload proof',true),reference=readFileSync(prior+'/week-8788.save.json','utf8');report.reference={path:prior+'/week-8788.save.json',sha256:sha(reference),bytes:Buffer.byteLength(reference)};assert(report.reference.sha256===old.checkpoints.find((p:any)=>p.week===8788).saveSha256,'Original final no longer matches bound old report');report.exactPriorFinal=finalBytes===reference;report.final=summary(state);report.final.saveBytes=Buffer.byteLength(finalBytes);report.final.saveSha256=sha(finalBytes);report.countsMatchPrior={};for(const key of ['week','studios','people','films','liveFilms','careerEvents','employmentIntervals','currentEmployment','receipts','concepts']){report.countsMatchPrior[key]=report.final[key]===old.final[key];if(!report.countsMatchPrior[key])report.errors.push({countMismatch:key,old:old.final[key],current:report.final[key]})}
 if(!report.exactPriorFinal){report.errors.push({message:'Current continuation final differs from original exact final bytes; no silent rebaseline',oldSha256:sha(reference),currentSha256:sha(finalBytes)});report.differences=differences(JSON.parse(reference),JSON.parse(finalBytes));writeFileSync(dir+'/differences.json',JSON.stringify(report.differences,null,2),{mode:0o600});}
 const sorted=[...tickTimes].sort((a,b)=>a-b);report.ticks.distribution={n:sorted.length,medianMs:sorted[Math.floor(sorted.length/2)],p95Ms:sorted[Math.ceil(sorted.length*.95)-1],maxMs:sorted.at(-1)};report.completed=report.errors.length===0;report.memoryAtFinish=process.memoryUsage();
}catch(error:any){report.completed=false;report.failedWeek=state?.market.tick??null;report.errors.push({message:error.message,stack:String(error.stack).split('\n').slice(0,8)});console.log(JSON.stringify({failedWeek:report.failedWeek,error:error.message}));}
finally{const before=JSON.parse(readFileSync(dir+'/source-before.json','utf8')),after=before.map((r:any)=>({...r,sha256:sha(readFileSync(r.absolutePath))}));report.sourceVerification={files:before.length,unchanged:before.every((r:any,i:number)=>r.sha256===after[i].sha256),changedPaths:before.filter((r:any,i:number)=>r.sha256!==after[i].sha256).map((r:any)=>r.path),binding:JSON.parse(readFileSync(dir+'/binding.json','utf8'))};if(!report.sourceVerification.unchanged){report.completed=false;report.errors.push({message:'Source changed during proof',paths:report.sourceVerification.changedPaths})}writeFileSync(dir+'/source-after.json',JSON.stringify(after,null,2),{mode:0o600});report.finish=new Date().toISOString();writeFileSync(dir+'/report.json',JSON.stringify(report,null,2),{mode:0o600});console.log(JSON.stringify({completed:report.completed,exactPriorFinal:report.exactPriorFinal,week:state?.market.tick,count:report.ticks.count,sourceUnchanged:report.sourceVerification.unchanged,errors:report.errors,report:dir+'/report.json'}));}
