// Independent T4 regressions: companion §4.1/§4.3/§4.4, P14B.1 scope (5)/(10),
// and evidence/p14b1-20260919-t4/05-review.md. Fixtures are generated by the
// recovered commands or migrated from the genuine V28 fixture. Only rejection
// cases mutate their serialized copies. No production observation sets a desired
// outcome, no test changes frozen validators, and no first take is fabricated.
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { gunzipSync } from 'node:zlib'
import { describe, expect, it, vi } from 'vitest'
import * as promiseModule from '../src/core/promises.js'
import { attachPromise, promiseFeasibility } from '../src/core/promises.js'
import { LIVE_SAVE_VERSION, migrateToLive, validateSaveV34 } from '../src/core/save.js'
import { advanceTo, p13aGeneratedStudio } from '../src/harness/p13a/fixtures.js'
import { tick } from '../src/core/tick.js'
import { fnv1a64 } from '../src/core/math.js'
import { submitProposal } from '../src/core/talentMarket.js'
import type { GameState, ProfessionalPromise, PromiseFeasibilityReceipt, TalentMarketProposal } from '../src/core/types.js'

const OPEN_CASE_SHA = 'c9ff26fe70b7216784bf5718ed26d2bef10df8ca836b05050f5e1d7bcaac8afd'
function openCase(): { state: GameState; proposal: TalentMarketProposal } {
  const json = gunzipSync(readFileSync(new URL('./fixtures/p14/legacy-v28-open-case-45.json.gz', import.meta.url))).toString('utf8')
  expect(createHash('sha256').update(json).digest('hex')).toBe(OPEN_CASE_SHA)
  const state = migrateToLive(JSON.parse(json)).state
  const proposal = state.talentMarket.proposals.find((p) => p.issuerStudioId === state.hollywood!.playerStudioId)!
  expect(proposal).toBeDefined()
  return { state, proposal }
}

function draftFor(proposal: TalentMarketProposal) {
  return {
    family: 'APPEARANCE_COUNT' as const,
    issuerStudioId: proposal.issuerStudioId,
    beneficiaryPersonId: proposal.talentId,
    predicate: { count: 1 },
    windowStartWeek: proposal.startWeek,
    dueWeekExclusive: proposal.startWeek + 40,
    startWeek: proposal.startWeek,
    termWeeks: proposal.termWeeks,
  }
}

let attachedCache: GameState | undefined
function attachedState(): GameState {
  if (attachedCache === undefined) {
    const { state, proposal } = openCase()
    attachedCache = attachPromise(state, proposal.talentId, proposal.issuerStudioId, draftFor(proposal))
  }
  return attachedCache
}
function ownPromise(state: GameState): ProfessionalPromise {
  const promise = state.promises.find((p) => p.issuerStudioId === state.hollywood!.playerStudioId)
  if (promise === undefined) throw new Error('fixture: no player promise')
  return promise
}

let boundCache: GameState | undefined
function boundState(): GameState {
  if (boundCache === undefined) {
    const attached = attachedState()
    const original = ownPromise(attached)
    boundCache = advanceTo(attached, original.windowStartWeek)
    const bound = ownPromise(boundCache)
    const row = boundCache.hollywood!.employment.find((e) => e.contractId === bound.contractId)
    expect(row).toBeDefined()
    expect(row!.studioId).toBe(bound.issuerStudioId)
    expect(row!.terms.talentId).toBe(bound.beneficiaryPersonId)
    expect(row!.terms.startWeek).toBe(original.windowStartWeek)
    expect(boundCache.talentMarket.receipts.some((r) => r.kind === 'settled'
      && r.talentId === bound.beneficiaryPersonId && r.studioId === bound.issuerStudioId)).toBe(true)
  }
  return boundCache
}

const envelope = (state: GameState) => ({ saveVersion: LIVE_SAVE_VERSION, seed: state.seed, state, broadcastCache: state.broadcastItems })
type Raw = {
  state: {
    promises: Record<string, unknown>[]
    firstTakes: Record<string, unknown>[]
    talentMarket: { proposals: Record<string, unknown>[]; receipts: Record<string, unknown>[] }
  }
}
function rejects(state: GameState, mutate: (raw: Raw) => void): void {
  const valid = JSON.parse(JSON.stringify(envelope(state))) as Raw
  expect(() => validateSaveV34(valid)).not.toThrow()
  mutate(valid)
  expect(() => validateSaveV34(valid)).toThrow()
}

describe('P14B.1 T4: feasibility evidence and lawful contract windows', () => {
  it('rejects a window starting before the proposed contract, while the exact start remains offerable', () => {
    const { state, proposal } = openCase()
    const draft = draftFor(proposal)
    expect(promiseFeasibility(state, draft, state.market.tick).classification).toBe('REASONABLY_ACHIEVABLE')
    const early = promiseFeasibility(state, { ...draft, windowStartWeek: proposal.startWeek - 1 }, state.market.tick)
    expect(early.classification).toBe('IMPOSSIBLE')
    expect(early.bottleneck).toMatch(/contract|start|window/i)
  })

  it('identifies changed committed reservations at the identical week, without mutation or RNG use', () => {
    const { state, proposal } = openCase()
    const draft = draftFor(proposal)
    const originalBytes = JSON.stringify(state)
    const before = promiseFeasibility(state, draft, state.market.tick)
    const reserved = attachPromise(state, proposal.talentId, proposal.issuerStudioId, draft)
    const reservedBytes = JSON.stringify(reserved)
    const after = promiseFeasibility(reserved, draft, reserved.market.tick)
    expect(reserved.market.tick).toBe(state.market.tick)
    expect(before.classification).toBe('REASONABLY_ACHIEVABLE')
    expect(after.classification).toBe('FRAGILE')
    expect(after.inputsDigest).not.toBe(before.inputsDigest)
    expect(promiseFeasibility(reserved, draft, reserved.market.tick)).toEqual(after)
    expect(reserved.rngState).toEqual(state.rngState)
    expect(JSON.stringify(state)).toBe(originalBytes)
    expect(JSON.stringify(reserved)).toBe(reservedBytes)
  })

  it('stores the actual winning freeze receipt at the decision week, not the submission receipt', () => {
    const attached = attachedState()
    const submitted = ownPromise(attached)
    const actualFeasibility = promiseModule.promiseFeasibility
    const freezeReceipts: PromiseFeasibilityReceipt[] = []
    // Transparent observer: every invocation executes the actual engine service.
    // Retain only this winner's calls BEFORE its new employment is committed.
    const spy = vi.spyOn(promiseModule, 'promiseFeasibility').mockImplementation((state, draft, week) => {
      const result = actualFeasibility(state, draft, week)
      const alreadyCommitted = state.hollywood!.employment.some((e) => e.studioId === submitted.issuerStudioId
        && e.terms.talentId === submitted.beneficiaryPersonId && e.terms.startWeek === submitted.windowStartWeek)
      if (week === submitted.windowStartWeek && draft.promiseId === submitted.promiseId && !alreadyCommitted) freezeReceipts.push(result)
      return result
    })
    let settled: GameState
    try { settled = advanceTo(attached, submitted.windowStartWeek) } finally { spy.mockRestore() }
    const bound = ownPromise(settled)
    expect(submitted.feasibilityReceipt.week).toBe(45)
    expect(bound.feasibilityReceipt.week).toBe(settled.market.tick)
    expect(bound.feasibilityReceipt.classification).toBe('REASONABLY_ACHIEVABLE')
    expect(bound.feasibilityReceipt.inputsDigest).not.toBe(submitted.feasibilityReceipt.inputsDigest)
    expect(freezeReceipts.length).toBeGreaterThan(0)
    expect(freezeReceipts).toContainEqual(bound.feasibilityReceipt)
  })
})

describe('P14B.1 T4: V29 owns every proposal promise leaf', () => {
  it('preserves an explicitly synthetic old-writer early window and submission receipt without rewriting real contract/outcome identity', () => {
    // Compatibility ruling, NOT a genuine historic fixture: derive a valid
    // bound/BROKEN state through today's commands, then substitute ONLY the two
    // facts d19's V29 writer could export. Its rules-v1 digest was the nine draft
    // inputs below, with no state component; retain that truthful old receipt.
    const state = advanceTo(boundState(), ownPromise(boundState()).dueWeekExclusive)
    const target = ownPromise(state)
    expect(target.outcome).toBe('BROKEN')
    const { state: submitted, proposal } = openCase()
    const oldWindowStart = submitted.market.tick
    expect(oldWindowStart).toBeLessThan(proposal.startWeek)
    const oldReceipt: PromiseFeasibilityReceipt = {
      classification: 'REASONABLY_ACHIEVABLE', bottleneck: null, rulesVersion: 1,
      week: submitted.market.tick,
      inputsDigest: fnv1a64(JSON.stringify([
        target.family, target.issuerStudioId, target.beneficiaryPersonId, target.predicate.count,
        oldWindowStart, target.dueWeekExclusive, proposal.startWeek, proposal.termWeeks, submitted.market.tick,
      ])),
    }
    const historicalVariant: GameState = { ...state, promises: state.promises.map((p) => p.promiseId === target.promiseId
      ? { ...p, windowStartWeek: oldWindowStart, feasibilityReceipt: oldReceipt } : p) }
    const json = JSON.stringify(envelope(historicalVariant))
    const loaded = validateSaveV34(JSON.parse(json))
    expect(JSON.stringify(loaded)).toBe(json)
    const retained = ownPromise(loaded.state)
    expect(retained.contractId).toBe(target.contractId)
    expect(retained.outcomeEventId).toBe(target.outcomeEventId)
    expect(retained.feasibilityReceipt).toEqual(oldReceipt)
    expect(retained.windowStartWeek).toBe(oldWindowStart)
  })

  it.each([
    ['missing', undefined], ['null', null], ['string', 'promise-0'], ['object', {}],
    ['non-string member', [0]], ['unknown reference', ['missing-promise']],
    ['duplicate reference', ['promise-0', 'promise-0']],
  ])('rejects a %s proposal promises leaf before it is stripped for frozen V28 validation', (_name, value) => {
    rejects(attachedState(), (raw) => {
      const proposal = raw.state.talentMarket.proposals.find((p) => p.issuerStudioId === attachedState().hollywood!.playerStudioId)!
      if (value === undefined) delete proposal.promises
      else proposal.promises = value
    })
  })

  it('rejects attaching another issuer\'s real promise ID to a proposal', () => {
    const state = attachedState()
    const promise = ownPromise(state)
    rejects(state, (raw) => {
      const rival = raw.state.talentMarket.proposals.find((p) => p.issuerStudioId !== promise.issuerStudioId)!
      rival.promises = [promise.promiseId]
    })
  })

  it('rejects a bound promise whose contract ID is absent', () => {
    rejects(boundState(), (raw) => { raw.state.promises[0]!.contractId = 'missing-employment' })
  })

  it('rejects a real contract ID belonging to a different beneficiary or issuer', () => {
    const state = boundState()
    const promise = ownPromise(state)
    const other = state.hollywood!.employment.find((e) => e.terms.talentId !== promise.beneficiaryPersonId)!
    expect(other).toBeDefined()
    rejects(state, (raw) => { raw.state.promises[0]!.contractId = other.contractId })
  })

  it.each(['missing contract field', 'wrong beneficiary', 'wrong issuer'])('rejects a bound promise with %s independently of the other pair field', (fault) => {
    const state = boundState()
    const promise = ownPromise(state)
    rejects(state, (raw) => {
      const row = raw.state.promises.find((p) => p.promiseId === promise.promiseId)!
      if (fault === 'missing contract field') delete row.contractId
      else if (fault === 'wrong beneficiary') row.beneficiaryPersonId = state.talent.find((p) => p.id !== promise.beneficiaryPersonId)!.id
      else row.issuerStudioId = state.hollywood!.identities.find((s) => s.enteredWeek !== null && s.studioId !== promise.issuerStudioId)!.studioId
    })
  })

  it('rejects the same pair\'s previous contract, whose interval cannot carry this window', () => {
    const state = boundState()
    const promise = ownPromise(state)
    const previous = state.hollywood!.employment.find((e) => e.terms.talentId === promise.beneficiaryPersonId
      && e.studioId === promise.issuerStudioId && e.contractId !== promise.contractId)!
    expect(previous).toBeDefined()
    rejects(state, (raw) => { raw.state.promises[0]!.contractId = previous.contractId })
  })

  it('rejects a terminal promise rebound to the same pair\'s later actual contract starting after its outcome', () => {
    const firstBound = boundState()
    const promised = ownPromise(firstBound)
    const originalEmployment = firstBound.hollywood!.employment.find((e) => e.contractId === promised.contractId)!
    const nextStart = originalEmployment.terms.endWeekExclusive
    let state = advanceTo(firstBound, nextStart - 8)
    expect(state.market.tick).toBe(96)
    expect(ownPromise(state).outcome).toBe('BROKEN')
    expect(ownPromise(state).outcomeWeek).toBe(92)
    state = submitProposal(state, { talentId: promised.beneficiaryPersonId,
      issuerStudioId: promised.issuerStudioId, termWeeks: 52, premiumTier: 1.25 })
    const proposal = state.talentMarket.proposals.find((p) => p.talentId === promised.beneficiaryPersonId
      && p.issuerStudioId === promised.issuerStudioId)!
    expect(proposal.startWeek).toBe(nextStart)
    expect(proposal.promises).toEqual([])
    state = advanceTo(state, nextStart)
    const laterEmployment = state.hollywood!.employment.find((e) => e.studioId === promised.issuerStudioId
      && e.terms.talentId === promised.beneficiaryPersonId && e.terms.startWeek === nextStart && e.endedWeek === null)!
    expect(laterEmployment).toBeDefined()
    expect(laterEmployment.contractId).not.toBe(promised.contractId)
    expect(state.talentMarket.receipts.some((r) => r.kind === 'settled' && r.week === nextStart
      && r.talentId === promised.beneficiaryPersonId && r.studioId === promised.issuerStudioId)).toBe(true)
    const terminal = ownPromise(state)
    expect(terminal.contractId).toBe(promised.contractId)
    expect(terminal.outcome).toBe('BROKEN')
    expect(laterEmployment.terms.startWeek).toBeGreaterThan(terminal.outcomeWeek!)
    expect(state.talentMarket.receipts.find((r) => r.eventId === terminal.outcomeEventId)?.kind).toBe('promiseOutcome')
    // Only the pointer changes. Both employment rows, the original outcome, and
    // the second lawful settlement remain untouched and individually real.
    rejects(state, (raw) => {
      raw.state.promises.find((p) => p.promiseId === terminal.promiseId)!.contractId = laterEmployment.contractId
    })
  })
})

// The recovered engine's natural rival chain authors its own actor promises,
// binds them at expiry, then films. Search the actual receipts for a take shared
// by multiple beneficiaries; never manufacture an outcome or guess an event ID.
let sharedCache: { state: GameState; promises: ProfessionalPromise[] } | undefined
function sharedTakeOutcomes(): { state: GameState; promises: ProfessionalPromise[] } {
  if (sharedCache !== undefined) return sharedCache
  let state = p13aGeneratedStudio()
  for (let week = 0; week <= 230; week++) {
    const groups = new Map<string, ProfessionalPromise[]>()
    for (const promise of state.promises) {
      if (promise.outcome !== 'SATISFIED') continue
      for (const eventId of promise.evidenceRefs) groups.set(eventId, [...(groups.get(eventId) ?? []), promise])
    }
    const shared = [...groups.values()].find((promises) => new Set(promises.map((p) => p.beneficiaryPersonId)).size >= 2)
    if (shared !== undefined) {
      sharedCache = { state, promises: shared }
      return sharedCache
    }
    state = tick(state)
  }
  throw new Error('fixture: no multi-beneficiary promise outcome from a shared real take within 230 weeks')
}

describe('P14B.1 T4: terminal V29 promise reference integrity', () => {
  it('round-trips several beneficiaries sharing one real take and distinct own outcome receipts', () => {
    const { state, promises } = sharedTakeOutcomes()
    expect(new Set(promises.map((p) => p.beneficiaryPersonId)).size).toBeGreaterThanOrEqual(2)
    expect(new Set(promises.map((p) => p.outcomeEventId)).size).toBe(promises.length)
    const shared = state.firstTakes.find((take) => promises.every((p) => p.evidenceRefs.includes(take.eventId)))!
    expect(shared).toBeDefined()
    for (const promise of promises) {
      const employment = state.hollywood!.employment.find((e) => e.contractId === promise.contractId)!
      expect(employment.terms.talentId).toBe(promise.beneficiaryPersonId)
      expect(employment.studioId).toBe(promise.issuerStudioId)
      expect(shared.studioId).toBe(promise.issuerStudioId)
      expect(Object.values(shared.cast)).toContain(promise.beneficiaryPersonId)
      const outcome = state.talentMarket.receipts.find((r) => r.eventId === promise.outcomeEventId)!
      expect(outcome.kind).toBe('promiseOutcome')
      expect(outcome.talentId).toBe(promise.beneficiaryPersonId)
      expect(outcome.studioId).toBe(promise.issuerStudioId)
      expect(outcome.week).toBe(promise.outcomeWeek)
    }
    const json = JSON.stringify(envelope(state))
    expect(JSON.stringify(validateSaveV34(JSON.parse(json)))).toBe(json)
  }, 120_000)

  it.each(['missing', 'null', 'unknown', 'wrong receipt kind', 'another beneficiary', 'wrong outcome week'])('rejects %s outcome receipt references', (fault) => {
    const { state, promises } = sharedTakeOutcomes()
    const target = promises[0]!
    rejects(state, (raw) => {
      const row = raw.state.promises.find((p) => p.promiseId === target.promiseId)!
      if (fault === 'missing') delete row.outcomeEventId
      else if (fault === 'null') row.outcomeEventId = null
      else if (fault === 'unknown') row.outcomeEventId = 'missing-market-event'
      else if (fault === 'wrong receipt kind') row.outcomeEventId = state.talentMarket.receipts.find((r) => r.kind !== 'promiseOutcome')!.eventId
      else if (fault === 'wrong outcome week') row.outcomeWeek = target.outcomeWeek! - 1
      else {
        // Swap two valid IDs so a uniqueness-only check cannot catch the fault.
        const sibling = raw.state.promises.find((p) => p.promiseId === promises[1]!.promiseId)!
        row.outcomeEventId = promises[1]!.outcomeEventId
        sibling.outcomeEventId = target.outcomeEventId
      }
    })
  })

  it.each(['missing take', 'non-take receipt', 'wrong studio or cast', 'empty', 'duplicate', 'outside window', 'wrong progress', 'unbound outcome'])('rejects %s qualifying evidence', (fault) => {
    const { state, promises } = sharedTakeOutcomes()
    const target = promises[0]!
    rejects(state, (raw) => {
      const row = raw.state.promises.find((p) => p.promiseId === target.promiseId)!
      if (fault === 'missing take') row.evidenceRefs = ['missing-first-take']
      else if (fault === 'non-take receipt') row.evidenceRefs = [target.outcomeEventId]
      else if (fault === 'wrong studio or cast') {
        const unrelated = state.firstTakes.find((t) => t.studioId !== target.issuerStudioId
          || !Object.values(t.cast).includes(target.beneficiaryPersonId))!
        expect(unrelated).toBeDefined()
        row.evidenceRefs = [unrelated.eventId]
      } else if (fault === 'empty') row.evidenceRefs = []
      else if (fault === 'duplicate') row.evidenceRefs = [target.evidenceRefs[0], target.evidenceRefs[0]]
      else if (fault === 'outside window') row.windowStartWeek = target.outcomeWeek! + 1
      else if (fault === 'wrong progress') row.progress = 0
      else row.contractId = null
    })
  })
})
