import {generateWorld} from './src/core/worldgen.ts';
import {initializeHollywood,enterRival} from './src/core/hollywood.ts';
import {tick} from './src/core/tick.ts';
import {makeSave,exportCurrentState,importSave} from './src/core/save.ts';
import {campaignDate} from './src/core/calendar.ts';
import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {performance} from 'node:perf_hooks';import {setImmediate as yieldNow} from 'node:timers/promises';import {cpus,totalmem,platform,release,arch} from 'node:os';
const dir='/tmp/p12a-core-entry-9i1pt852',prior='/tmp/p12a-engineering-8788-P6KEMm',seed='r05-living-hollywood';
const arrivals=[0,0,0,0,520,988,1560,1872,2548],capital=[32000000,29000000,23000000,20000000,24000000,26000000,34000000,28000000,38000000],thresholds=arrivals.slice(4),neighbors=new Set(thresholds.flatMap(w=>[w-1,w,w+1]));
const sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex'),assert=(yes:boolean,msg:string)=>{if(!yes)throw new Error(msg)};
const old=JSON.parse(readFileSync(prior+'/report.json','utf8'));
const report:any={purpose:'Independent CURRENT pure-core fresh0→2548 applicability proof plus isolated2549 arrival-after tick; no implementation restart, bridge/native acceptance or second6240 run',start:new Date().toISOString(),commit:'6827293985a1375e8cefed745fbc4227a01aeb53',seed,driver:"initializeHollywood(generateWorld(seed),'fresh'); tick(state,{develop:true}); no player actions",runtime:process.version,execArgv:process.execArgv,hardware:{platform:platform(),release:release(),arch:arch(),cpu:cpus()[0]?.model,logicalCpus:cpus().length,totalMemoryBytes:totalmem()},validations:[],arrivalChecks:[],checks:[],errors:[],completed:false,ticks:{count:0,totalMs:0,maxMs:0}};
let state:any,rng:any,stop=false;process.on('SIGTERM',()=>{stop=true});process.on('SIGINT',()=>{stop=true});
const persist=()=>writeFileSync(dir+'/report-progress.json',JSON.stringify(report,null,2),{mode:0o600});
function calendar(s:any){const date=campaignDate(s.market.tick),year=1920+Math.floor(s.market.tick/52),week=1+s.market.tick%52;assert(date.absoluteWeek===s.market.tick&&date.year===year&&date.weekOfYear===week&&date.label===year+' · Week '+week,'Calendar mismatch at '+s.market.tick);assert(date.policy==='campaign-calendar-1920-52/v1'&&s.hollywood.calendarPolicy===date.policy,'Calendar policy mismatch');return date}
const validate=(s:any)=>{const started=performance.now();makeSave(s);report.validations.push({week:s.market.tick,ms:performance.now()-started});};
function checkEntries(s:any,tag:string){const week=s.market.tick,h=s.hollywood,expected=arrivals.filter(w=>w<=week).length;assert(h.businesses.length===expected,'Wrong number of businesses at '+week);assert(s.rngState===rng,'Player RNG changed');const details=[];
 for(let i=0;i<9;i++){const id=h.identities.find((x:any)=>x.role==='rival'&&x.row===i+1);assert(id&&id.eligibleWeek===arrivals[i],'Wrong scheduled identity eligibility');const businesses=h.businesses.filter((b:any)=>b.studioId===id.studioId),entry=h.receipts.filter((r:any)=>r.studioId===id.studioId&&r.kind==='studioEntered'),due=arrivals[i]!;
  if(due>week){assert(id.enteredWeek===null&&id.recordedFromWeek===null&&businesses.length===0&&entry.length===0,'Rival appeared before eligibility');assert(!h.employment.some((e:any)=>e.studioId===id.studioId)&&!h.receipts.some((r:any)=>r.studioId===id.studioId),'Future rival has employment or receipt');let refused=false;try{enterRival(s,id.studioId,'scheduled')}catch{refused=true}assert(refused,'Entry before eligible date did not refuse');details.push({name:id.name,due,present:false});continue}
  assert(businesses.length===1&&entry.length===1,'Rival entry not exactly once');const b=businesses[0],e=entry[0];assert(id.enteredWeek===due&&id.recordedFromWeek===due&&e.week===due&&e.entryKey===b.entryKey,'Entry identity/date mismatch');assert(e.origin===(i<4?'fresh':'scheduled'),'Entry origin mismatch');assert(b.account.openingBalance===capital[i]&&b.account.openingBasis==='before-capacity-and-signing'&&b.account.periods[0].opening===capital[i],'Single endowment mismatch');const capacity=b.account.periods.reduce((n:number,p:any)=>n+p.movements.capacity,0);assert(capacity===-5900000,'Capacity was not paid exactly once');const initialContracts=h.employment.filter((row:any)=>row.studioId===id.studioId&&row.reason==='entry');assert(initialContracts.length===6,'Entry team is not exactly six');const signing=initialContracts.reduce((n:number,row:any)=>n+row.terms.signingBonus,0);assert(b.account.periods[0].movements.signing===-signing,'Entry signing charges differ from actual six contracts');const employmentReceipts=h.receipts.filter((r:any)=>r.studioId===id.studioId&&r.kind==='employment'&&r.reason==='entry');assert(employmentReceipts.length===6&&new Set(employmentReceipts.map((r:any)=>r.contractId)).size===6,'Entry employment receipt duplicate');for(const c of initialContracts)assert(c.terms.startWeek===due,'Initial contract start differs');assert(enterRival(s,id.studioId,e.origin)===s,'Duplicate entry modified authority or re-endowed rival');
  if(week===due){const expectedCash=initialContracts.reduce((n:number,row:any)=>n-row.terms.signingBonus,capital[i]!-5900000);assert(b.account.cash===expectedCash,'Entry cash does not equal capital less once-only capacity/signing');assert(b.account.periods.length===1,'Entry unexpectedly has prior financial periods');}
  details.push({name:id.name,due,present:true,entryReceipts:entry.length,capital:b.account.openingBalance,capacity,initialSigning:signing,initialContracts:initialContracts.length,duplicateEntryNoOp:true});
 }
 assert(initializeHollywood(s,'fresh')===s,'Reinitialization modified existing authority');const date=calendar(s);report.arrivalChecks.push({tag,week,expected,actual:h.businesses.length,date,playerRngUnchanged:true,details});console.log(JSON.stringify({arrivalCheck:week,date:date.label,businesses:h.businesses.length,tag}));persist();}
const count=(s:any)=>({week:s.market.tick,studios:s.hollywood.businesses.length,people:s.talent.length,films:s.hollywood.films.length,liveFilms:s.hollywood.films.filter((f:any)=>f.provenance==='simulation/v1').length,careerEvents:s.hollywood.careerEvents.length,employmentIntervals:s.hollywood.employment.length,currentEmployment:s.hollywood.activeEmploymentOrdinals.length,receipts:s.hollywood.receipts.length,concepts:s.hollywood.concepts.length,rngState:s.rngState});
const samples:number[]=[];
try{const world=generateWorld(seed);rng=world.rngState;state=initializeHollywood(world,'fresh');assert(state.market.tick===0&&state.rngState===rng,'Fresh initialization changed tick or player RNG');validate(state);checkEntries(state,'initial four incumbents');report.initial=count(state);
 while(state.market.tick<2548){if(stop)throw new Error('Interrupted for explicit stop or native priority');const before=state.market.tick,started=performance.now();state=tick(state,{develop:true});const ms=performance.now()-started;report.ticks.count++;report.ticks.totalMs+=ms;report.ticks.maxMs=Math.max(report.ticks.maxMs,ms);samples.push(ms);assert(state.market.tick===before+1,'Ordinary tick did not advance one week');assert(state.rngState===rng,'Player RNG changed at '+state.market.tick);calendar(state);if(state.market.tick%52===0||neighbors.has(state.market.tick))validate(state);if(neighbors.has(state.market.tick))checkEntries(state,thresholds.includes(state.market.tick)?'due':'neighbor');if(state.market.tick%52===0)await yieldNow();}
 assert(report.ticks.count===2548,'Wrong fresh trace length');const bytes=exportCurrentState(state),reference=readFileSync(prior+'/week-2548.save.json','utf8'),oldPoint=old.checkpoints.find((p:any)=>p.week===2548);report.final={...count(state),bytes:Buffer.byteLength(bytes),sha256:sha(bytes)};report.reference={path:prior+'/week-2548.save.json',bytes:Buffer.byteLength(reference),sha256:sha(reference)};assert(report.reference.sha256===oldPoint.saveSha256,'Original artifact differs from its prior source-bound report');report.exactPriorFinal=bytes===reference;writeFileSync(dir+'/week-2548.save.json',bytes,{mode:0o600});if(!report.exactPriorFinal)throw new Error('Current fresh trace differs from prior exact week2548 bytes; stop without rebaseline');report.countsMatchPrior={};for(const k of ['week','studios','people','films','liveFilms','careerEvents','employmentIntervals','currentEmployment','receipts','concepts']){report.countsMatchPrior[k]=report.final[k]===oldPoint[k];assert(report.countsMatchPrior[k],'Final count differs: '+k)}
 const loaded=importSave(bytes);assert(loaded.saveVersion===19,'Reload save version changed');assert(exportCurrentState(loaded.state)===bytes,'Final canonical reload mismatch');const next=tick(state,{develop:true}),loadedNext=tick(loaded.state,{develop:true});validate(next);checkEntries(next,'isolated last-arrival after tick');assert(next.market.tick===2549,'Isolated next tick mismatch');const nextBytes=exportCurrentState(next);assert(nextBytes===exportCurrentState(loadedNext),'Final fresh/reload next tick differs');const continuation=JSON.parse(readFileSync('/tmp/p12a-core-resume-t7c16t09/report.json','utf8'));assert(sha(nextBytes)===continuation.checkpoints[0].nextTickSha256,'Fresh trace next tick differs from verified continuation input next tick');report.after={...count(next),date:calendar(next),saveSha256:sha(nextBytes),exactReloadNextTick:true,matchesCurrentContinuationInputNextTick:true};
 const sorted=[...samples].sort((a,b)=>a-b);report.ticks.distribution={medianMs:sorted[Math.floor(sorted.length/2)],p95Ms:sorted[Math.ceil(sorted.length*.95)-1],maxMs:sorted.at(-1)};report.originalReferenceUnchanged=sha(readFileSync(report.reference.path))===report.reference.sha256;assert(report.originalReferenceUnchanged,'Original reference changed');report.completed=true;report.memoryAtFinish=process.memoryUsage();
}catch(e:any){report.completed=false;report.failedWeek=state?.market.tick;report.errors.push({message:e.message,stack:String(e.stack).split('\n').slice(0,8)});console.log(JSON.stringify({FAILED:e.message,week:state?.market.tick}));}
finally{const before=JSON.parse(readFileSync(dir+'/source-before.json','utf8')),after=before.map((r:any)=>({...r,sha256:sha(readFileSync(r.absolutePath))}));report.sourceVerification={files:before.length,unchanged:before.every((r:any,i:number)=>r.sha256===after[i].sha256),changedPaths:before.filter((r:any,i:number)=>r.sha256!==after[i].sha256).map((r:any)=>r.path),binding:JSON.parse(readFileSync(dir+'/binding.json','utf8'))};if(!report.sourceVerification.unchanged){report.completed=false;report.errors.push({message:'Source changed during proof',paths:report.sourceVerification.changedPaths})}writeFileSync(dir+'/source-after.json',JSON.stringify(after,null,2),{mode:0o600});report.finish=new Date().toISOString();writeFileSync(dir+'/report.json',JSON.stringify(report,null,2),{mode:0o600});console.log(JSON.stringify({completed:report.completed,exactPriorFinal:report.exactPriorFinal,week:state?.market.tick,ordinaryTicks:report.ticks.count,checks:report.arrivalChecks.length,sourceUnchanged:report.sourceVerification.unchanged,errors:report.errors,report:dir+'/report.json'}));}
