def authenticate_current_protection(g,c):
 p=load(g['currentProtection']);need(g['currentProtection']==c['currentProtection'],'EXACT_CURRENT_PROTECTION_ROLE')
 need(p['schema']=='1370-root-fullfunction-current-protection/v2' and p['status']=='ROOT_ADOPTED_CURRENT_FULLFUNCTION_PREFLIGHT_UNDER_CONTINUOUS_FREEZE' and p['productionHead']==c['operationalHead'] and p['productionSourceTree']==c['productionSourceTree'] and p['historicalTypesAdoption']==g['typesAdoption']==c['historicalTypesAdoption'] and p['historicalTypesHead']==c['historicalTypesHead'] and p['protectedFreezeContinues'] is True and p['executionAuthorization'] is False,'CURRENT_FULLFUNCTION_PROTECTION_V2')
 need(p['currentANFullPreflightAdoption']==c['actualCurrentANFullPreflightAdoption'] and p['currentOperationalTransition']==c['actualCurrentOperationalTransition'] and p['reviewedPriorStopAdoption']==c['reviewedPriorStopAdoption'],'CURRENT_AN_AUTHORITY_ROLES')
 a=load(p['currentANFullPreflightAdoption']);need(a['schema']=='1370-ao-root-current-an-fullpreflight-adoption/v1' and a['status']=='ROOT_ADOPTED_CURRENT_AN_FULL_PREFLIGHT' and a['productionHead']==c['operationalHead'] and a['productionSourceTree']==c['productionSourceTree'] and a['protectedFreezeContinues'] is True and a['executionAuthorization'] is False and p['currentANFullPreflightSnapshot']==a['snapshot'],'CURRENT_AN_FULL_PREFLIGHT')
 for k in ['actualReadback','independentObservedReview','snapshot','snapshotPins','guardSource','config','sourcePins','actualTool','postOwnership','rawLocalOnlyClassification']:read(a[k],16*1024**2)
 transition=load(p['currentOperationalTransition']);need(transition['schema']=='1370-ao-current-an-operational-transition/v1' and transition['actualHead']==c['operationalHead'] and transition['predecessor']==c['historicalTypesHead'] and transition['sourceTree']==c['productionSourceTree'] and transition['docsOnlyVerified'] is True and transition['workingTreeClean'] is True and transition['executionAuthorization'] is False,'HISTORICAL_TYPES_CURRENT_AN_CONTINUITY');read(transition['publishedReadback'])
 for k in ['actualPreflight','actualPreflightReadback','independentPreflightReview','reviewedPriorStopAdoption']:read(p[k],16*1024**2)
 return p
