import hashlib,json,os,sys
from pathlib import Path
S=Path('/Users/zacheryspector/studio-scratch');A=S/'1370-am-root-continuation-20261009-r1'
P=S/'1370-c0-m0-types-parent-recorded-after-al-20261009-r6';F=S/'1370-c0-m0-types-fullguard-postflight-parent-after-al-20261009-r3'
def role(p):
 p=Path(p);b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
assert len(sys.argv)==3 and sys.flags.isolated and sys.dont_write_bytecode and not sys.flags.optimize
rp=Path(sys.argv[1]);rr=role(rp);assert rr['sha256']==sys.argv[2]
rv=json.loads(rp.read_bytes());assert rv['decision']=='ACCEPT_OBSERVED_M0_TYPES_AND_DIAGNOSTIC_COLLECTION_WITH_FULL_PROTECTED_POSTFLIGHT' and rv['concreteFindings']==[]
rb=json.loads((P/'READBACK.json').read_bytes());assert rb['mode']=='types' and rb['toolExit']==rb['helperExit']==rb['recorderExit']==rb['runnerExit']==0 and rb['laneReleased'] is True and rb['fourChildExitsZero'] is True and rb['fourChildRootBoundariesEqual'] is True and rb['sourceProofsEqual'] is True and rb['dependencyProofsEqual'] is True
pre=json.loads((A/'M0-TYPES-PREFLIGHT-OBSERVED-ADOPTION-R6.json').read_bytes());assert pre['status']=='ROOT_ADOPTED_ORIGINAL_CURRENT_ROOT_PREFLIGHT' and pre['mode']=='types' and pre['toolExit']==0
post=json.loads((F/'POSTFLIGHT-READBACK.json').read_bytes());assert post['mode']=='types' and post['actualToolExit']==post['scannerExit']==0 and post['immutableBaselineEquality'] is True and post['previousAcceptedPostflightEquality'] is True and post['protectedFreezeContinues'] is True
for r in [rb['typesResult'],rb['collection'],post['snapshot'],post['pins'],post['postOwnership'],post['actualTool']]:assert role(r['path'])==r
v=json.loads(Path(rb['typesResult']['path']).read_bytes());assert v['status']=='PASS_M0_TYPES_AND_DIAGNOSTIC_COLLECTION_ONLY' and v['h13MetadataStopWaived'] is False and v['gameAccepted'] is False
prot=json.loads((A/'M0-CURRENT-TYPES-PROTECTION-R6.json').read_bytes());assert v['sourceBefore']==v['sourceAfter']==prot['freshSourceProof'] and v['nodeModulesBefore']==v['nodeModulesAfter']==prot['freshDependencyProof']
proof=json.loads((A/'M0-CURRENT-PROOF-OBSERVED-ADOPTION.json').read_bytes());assert proof['status']=='ROOT_ADOPTED_CURRENT_M0_SOURCE_DEPENDENCY_PROOF_WITH_FULL_POSTFLIGHT'
assert role(proof['fullPostflightSnapshot']['path'])==proof['fullPostflightSnapshot'] and json.loads(Path(post['snapshot']['path']).read_bytes())['immutable']==json.loads(Path(proof['fullPostflightSnapshot']['path']).read_bytes())['immutable']
assert not os.path.lexists(S/'HEAVY-LANE-LOCK')
d={'schema':'1370-root-m0-types-observed-adoption/v1','status':'ROOT_ADOPTED_M0_TYPES_AND_DIAGNOSTIC_COLLECTION_WITH_FULL_PROTECTED_POSTFLIGHT','executionAuthorization':False,'independentObservedReview':rr,'actualTypesReadback':role(P/'READBACK.json'),'actualTypesResult':rb['typesResult'],'actualTypesPreflight':role(A/'M0-TYPES-PREFLIGHT-OBSERVED-ADOPTION-R6.json'),'currentSourceDependencyProofAdoption':role(A/'M0-CURRENT-PROOF-OBSERVED-ADOPTION.json'),'currentTypesProtection':role(A/'M0-CURRENT-TYPES-PROTECTION-R6.json'),'fullPostflightReadback':role(F/'POSTFLIGHT-READBACK.json'),'fullPostflightSnapshot':post['snapshot'],'productionHead':v['productionHead'],'productionSourceTree':v['productionSourceTree'],'sourceCommit':v['sourceCommit'],'historicalDataAuthorityHead':v['historicalDataAuthorityHead'],'physicalFactsSha256':v['physicalFactsSha256'],'completeM0AdoptionSha256':v['completeM0AdoptionSha256'],'fourCommands':rb['children'],'fourChildExitsZero':True,'fourChildRootBoundariesEqual':True,'sourceDependencyProofsEqual':True,'fullProtectedPostflightAccepted':True,'allImmutableMapsEqual':True,'collection':rb['collection'],'preparationElapsedSeconds':rb['preparationElapsedSeconds'],'runnerElapsedSeconds':rb['runnerElapsedSeconds'],'recorderElapsedSeconds':rb['recorderElapsedSeconds'],'recordedOwnedIds':rb['recordedOwnedIds'],'postOwnership':post['postOwnership'],'soleLaneReleased':True,'protectedFreezeContinues':True,'typesAndCollectionAccepted':True,'h13HistoricalFailureWaived':False,'controlsAccepted':False,'neutralCaptureAccepted':False,'gameAccepted':False,'scope':'Observed current M0 dependency-version check, root TypeScript check, UI TypeScript check and diagnostic collection only. No diagnostic execution, wiring controls, neutral416 game or broader1363 acceptance is implied.'}
p=A/'M0-TYPES-OBSERVED-ADOPTION.json'
with p.open('x') as f:json.dump(d,f,sort_keys=True,indent=2);f.write('\n');f.flush();os.fsync(f.fileno())
p.chmod(0o444);print(json.dumps(role(p)))
