import hashlib,json,os
from pathlib import Path
S=Path('/Users/zacheryspector/studio-scratch');A=S/'1370-am-root-continuation-20261009-r1';R=S/'1370-c0-renewal208-pure16-pricing-independent-observed-review-after-al-20261009-r1/RECEIPT.json';P=S/'1370-c0-renewal208-pure16-pricing-parent-recorded-after-al-20261009-r1';O=S/'1370-c0-renewal208-pure16-pricing-verification-output-after-al-20261009-r1'
def role(p):
 p=Path(p);b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
rr=role(R);assert rr['sha256']=='4610a4eeb858466c874d4b9bb2d1a51a35c268b450a93e12df44f12f9f5a6028';r=json.loads(R.read_bytes());assert r['decision']=='ACCEPT_OBSERVED_PURE16_RENEWAL208_PRICING_AND_SOURCE_TRANSPORTED_CAUSES' and not r['concreteFindings'] and r['renewalCauseAdmission'] is True and r['recordedPricingObservedAccepted'] is True and r['controlsObservedAccepted'] is True
for ref in r['reviewArtifacts'].values():assert role(ref['path'])==ref
v=json.loads((O/'stdout.bin').read_bytes());assert (v['selectedRows'],v['immutablePairs'],v['mismatches'])==(16,44,0);rows=v['ledger'];assert [x['sourceOrder'] for x in rows]==list(range(24,40)) and len({json.dumps(x['identity']) for x in rows})==16
assert all(x['completeH'] and x['completeA'] and x['HActual']==x['HPredicted'] and x['AActual']==x['APredicted'] for x in rows)
readback=json.loads((P/'READBACK.json').read_bytes());assert readback['toolExit']==readback['helperExit']==readback['recorderExit']==readback['nodeExit']==0 and readback['laneReleased'];assert not os.path.lexists(S/'HEAVY-LANE-LOCK')
assert r['renewalCauseAdmissionScope']['ageOnlyPersonRows']==5 and r['renewalCauseAdmissionScope']['ageAndOtherPersonRows']==11 and r['renewalCauseAdmissionScope']['originalOfferLocalCapture'] is False
out={'schema':'1370-root-pure16-renewal208-observed-pricing-adoption/v1','status':'ROOT_ADOPTED_OBSERVED_16_RENEWAL_PRICING_PAIRS_AND_SOURCE_TRANSPORTED_CAUSES','independentObservedReview':rr,'sourcePins':r['sourcePins'],'config':r['config'],'actualReadback':role(P/'READBACK.json'),'actualTool':role(P/'ACTUAL-TOOL.json'),'actualResult':role(O/'RESULT.json'),'actualPricingLedger':role(O/'stdout.bin'),'actualControlsRootAdoption':role(A/'PURE16-CONTROLS-OBSERVED-ADOPTION.json'),'actualA208RootAdoption':role(A/'A208-GAME-OBSERVED-ADOPTION.json'),'selectedRows':16,'immutablePairs':44,'mismatches':0,'all16AnnualAndBonusAndFullTermsAgree':True,'stableIdentityOccurrenceAndOrderAccepted':True,'renewalCauseAdmission':True,'renewalCauseAdmissionScope':r['renewalCauseAdmissionScope'],'independentFiniteDataChecks':229,'elapsedSeconds':readback['elapsedSeconds'],'qualifiedRecorderWarningRetained':True,'priorFailuresPreserved':True,'whole1363Admission':False,'AM0Admission':False,'P17P18Admission':False,'productionMutation':False,'originalOfferLocalCapture':False,'executionAuthorization':False,'next':'Carry admitted complete-vector renewal ledger into residual1363 reconciliation. M0 current proof/types/wiring/neutrality and A-to-M0/protected digests/unmatched identities remain separate.'}
p=A/'PURE16-PRICING-OBSERVED-ADOPTION.json'
with p.open('x') as f:json.dump(out,f,sort_keys=True,indent=2);f.write('\n');f.flush();os.fsync(f.fileno())
p.chmod(0o444);print(json.dumps(role(p)))
