import json,hashlib,os,sys
from pathlib import Path
S=Path('/Users/zacheryspector/studio-scratch');A=S/'1370-am-root-continuation-20261009-r1';G=S/'1370-c0-a208-game-parent-recorded-after-al-20261009-r4';P=S/'1370-c0-a208-fullguard-postflight-parent-after-al-20261009-r4'
def role(p):
 p=Path(p);b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
assert len(sys.argv)==3
rr=role(sys.argv[1]);assert rr['sha256']==sys.argv[2];r=json.loads(Path(sys.argv[1]).read_bytes());assert r['decision'].startswith('ACCEPT_OBSERVED') and r['executionAuthorization'] is False
roles={'A208SourcePins':role(S/'1370-c0-aging-era-settlement208-observer-after-aj-proposal-20261009-r1/SOURCE-PINS.json'),'A208Config':role(S/'1370-c0-a208-game-exact-filled-after-al-20261009-r4/BINDING-DRAFT.json'),'A208Result':role(G/'QUALIFIED-DERIVED-SUCCESS.json'),'A208Stdout':role(G/'candidate-frame.stdout'),'A208Snapshot':role(G/'settlement208.json'),'A208IndependentReceipt':rr}
for field,key in [('sourcePinsSha256','A208SourcePins'),('configSha256','A208Config'),('resultSha256','A208Result'),('stdoutSha256','A208Stdout'),('snapshotSha256','A208Snapshot')]:assert r[field]==roles[key]['sha256']
pr=json.loads((P/'POSTFLIGHT-READBACK.json').read_bytes());assert pr['actualToolExit']==0 and pr['immutableBaselineEquality'] is True and pr['afterFillEquality'] is True
f=json.loads((G/'candidate-frame.stdout').read_bytes());assert f['weeks']==416 and f['employmentRows']==44 and f['settlement208Rows']==16
assert f['preflight']==f['postflight']==f['finalflight']
d={'schema':'1370-root-a208-selected16-full416-observed-adoption/v1','status':'ROOT_ADOPTED_OBSERVED_A208_SELECTED16_AND_FULL416','independentReview':rr,'roles':roles,'exactGrant':role(G/'FINAL-GAME-GRANT.json'),'actualTool':role(G/'ACTUAL-TOOL.json'),'actualGameReadback':role(G/'ACTUAL-GAME-READBACK.json'),'postflightReadback':role(P/'POSTFLIGHT-READBACK.json'),'postflightSnapshot':pr['snapshot'],'originalBaseline':role(S/'1370-c0-a208-fullguard-game-filled-after-al-20261009-r1/evidence/before-fill-after-al-r1/SNAPSHOT.json'),'afterFill':role(S/'1370-c0-a208-fullguard-game-filled-after-al-20261009-r1/evidence/after-fill-after-al-game-r4/SNAPSHOT.json'),'fullImmutableMapsEqual':True,'full416AndOriginal44Accepted':True,'naturalSelected16Week208Accepted':True,'naturalCapturePhase':'after-natural-tick208-return','digests':f['digests'],'sourceFlightsEqual':True,'producerElapsedMs':f['elapsedMs'],'noPreciseWholeRecorderTimingClaim':True,'actualExits':{'tool':0,'helper':0,'helperMeta':0,'outer':0,'sink':0},'knownNumericGameHelper':34390,'knownNumericPostflightScanner':42893,'numericSupervisorAndNodeUnknown':True,'sourceQualifiedInternalCleanupAccepted':True,'derivedResultIsNotOriginalRecorderArtifact':True,'sourceRoleAndFramingQualificationInSameIndependentReview':True,'protectedFreezeContinues':True,'executionAuthorization':False,'renewalCauseAdmission':False,'M0TypesOrNeutralityAccepted':False,'C0Or1363OrH8708Accepted':False,'P17P18Accepted':False,'next':'Fill unchanged accepted pure16 verifier from these actual roles; exact filled source review, finite protocol controls, actual pricing and independent16/44 attribution still required.'}
p=A/'A208-GAME-OBSERVED-ADOPTION.json'
with p.open('x') as out:json.dump(d,out,sort_keys=True,indent=2);out.write('\n');out.flush();os.fsync(out.fileno())
p.chmod(0o444);print(json.dumps(role(p)))
