import hashlib,json,os
from pathlib import Path
A=Path('/Users/zacheryspector/studio-scratch/1370-am-root-continuation-20261009-r1')
b=(A/'LESSONS-r21.md').read_bytes();assert hashlib.sha256(b).hexdigest()=='efe3afd635d51a1c0d3d21487773fa15a3c4f36c0b17212318ffa9fb549aaf06'
p=A/'M0-R6-METADATA-STOP-OBSERVED-ADOPTION.json';ad=json.loads(p.read_bytes());assert ad['sharedR9DependencyFullPostflightAccepted'] is True and ad['m0SourcePreservationAccepted'] is False and ad['typesAccepted'] is False
b+=('''\n## A shared protection scan cannot repair another copy's failed metadata proof\n\nActual original fullpostflight98815 exits0 in502.316887605 seconds, inventory393.443869605. Snapshot7bd5b6ee equals the complete accepted immutable shared/R9/dependency baseline; all nine strict roots and eight scoped process/group absence checks pass. Independent '''+ad['independentObservedReview']['sha256']+''' and root '''+hashlib.sha256(p.read_bytes()).hexdigest()+''' admit the observed R6 STOP with this separately scoped shared protection. They do not fill the absent M0 sourceAfter/dependencyAfter proofs, pass types/collection, or explain the M0 root timestamp mutation. Keep the scope of each proof explicit even when every adjacent check succeeds. The completed scan is reused for its genuine outcome rather than replayed because a report or compiler failed.\n\n## Inspect the dependency actually used, and move tool writes instead of weakening guards\n\nStatic source examination resolves Vitest2.1.9's nested Vite5.4.21, not the top-level Vite6.4.3. Its ESM configuration loader writes a temporary timestamped module beside the source configuration and removes it afterward. This is a plausible mechanism for identical final directory entries with changed timestamps; static source alone is not a captured R6 file event. Redirecting a cache alone does not move that configuration sibling, and a flag supported by a different Vite version is not a fix for the installed loader.\n\nReviewed direction3341/root1aba12bd keeps strict metadata protection, externalizes every loaded root/workspace/project configuration, and preserves all original resolution, includes, aliases and collection semantics. First demonstrate a real nested-loader metadata RED and external-config GREEN on a disposable fixture with equal collection; separately verify complete current M0 content and all nonroot metadata and qualify the known root drift with evidence. Do not restore timestamps, recopy accepted historical source, silently repin unexplained state or infer a passed route from four child zero exits. This direction is prospective: no disposable-control or corrected M0 run is accepted in this checkpoint.\n''').encode()
p=A/'LESSONS-r22.md'
with p.open('xb') as f:f.write(b);f.flush();os.fsync(f.fileno())
p.chmod(0o444);print(json.dumps({'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}))
