#!/usr/bin/env python3
"""Reproduces the paper-scenario arithmetic used in the P15 independent verification report.

Pure Python, no dependencies, no game code. Run:  python3 reproduce.py > OUTPUT.md
Every figure is PROVISIONAL / HYPOTHETICAL unless stated to be a code constant at 592e926.
"""
import math

# ---- code constants at accepted TypeScript 592e926 (src/core/tuning.ts unless noted) ----
TICKS_PER_YEAR = 52
THEATRICAL_WEEKS = 6
PRODUCTION_TICKS = 8
INITIAL_CASH = 20_000_000
OVERHEAD_BASE, OVERHEAD_PER_EMPLOYEE = 15_000, 1_500
STUDIO_RENTAL_BLENDED = 0.52
FACILITY_REFUND, SET_REFUND = 0.50, 0.35            # tuning.ts demolition / strike fractions
HIRING_TERMINATION_FRACTION = 0.5
RIVAL_ARRIVAL_WEEKS = [0, 0, 0, 0, 520, 988, 1560, 1872, 2548]   # src/core/calendar.ts:3
GENRES = ['romance', 'horror', 'comedy', 'adventure', 'drama', 'crime']
# authored rival anchors (src/core/hollywoodStartingData.ts); weight 5 if anchor else 1 (hollywood.ts:156)
ANCHORS = {
    'Bellwether': ['comedy'], 'Rose Lantern': ['romance'], 'Night Orchard': ['horror'], 'Silver Current': ['romance'],
    'Marigold': ['romance'], 'Blackthorn': ['horror'], 'Trailhead': ['adventure'],
    'Copper Kite': ['horror', 'comedy'], 'Bright Meridian': ['comedy', 'adventure'],
}

def h(t): print('\n## ' + t + '\n')

print('# Reproduced calculations (PROVISIONAL)\n')
print('Generated by `calculations/reproduce.py`. Code constants are cited to `592e926`; everything else is hypothetical.')

# ---------------------------------------------------------------- 1. weekly amortization
h('1. Fixed-term amortizing loans — weekly payments (52/yr)')
def weekly_payment(P, annual_rate, years):
    r = annual_rate / TICKS_PER_YEAR; n = years * TICKS_PER_YEAR
    return P * r / (1 - (1 + r) ** -n)
print('| Principal | Rate | Term | Weekly payment | Total paid | Total interest | Interest ÷ principal |')
print('|---|---|---|---|---|---|---|')
for P in (1_000_000, 5_000_000, 20_000_000):
    for rate in (0.06, 0.08, 0.12):
        for yrs in (5, 10):
            w = weekly_payment(P, rate, yrs); tot = w * yrs * TICKS_PER_YEAR
            print(f'| ${P:,} | {rate:.0%} | {yrs} yr | ${w:,.0f} | ${tot:,.0f} | ${tot-P:,.0f} | {(tot-P)/P:.1%} |')

# ---------------------------------------------------------------- 2. leverage vs coverage
h('2. Leverage cap vs coverage floor (8 % / 10 yr Studio Loan)')
surplus = 1_500_000
w = weekly_payment(1, 0.08, 10) * TICKS_PER_YEAR          # annual service per $ of principal
for lev in (2.0, 2.29, 3.0):
    debt = lev * surplus; service = debt * w
    print(f'- leverage {lev:.2f}× → debt ${debt:,.0f}, annual service ${service:,.0f}, coverage {surplus/service:.2f}×')
print(f'- debt at exactly 3× coverage: ${surplus/3/w:,.0f}  (≈ {surplus/3/w/surplus:.2f}× leverage) — coverage binds before the 3× leverage cap')

# ---------------------------------------------------------------- 3. release-window probabilities
h('3. Probability a rival same-genre release lands inside a window')
films_per_rival_per_year = 2.0   # Prima p.82 "10 in five years" used as the illustrative rate
rate = {g: 0.0 for g in GENRES}
for studio, anchors in ANCHORS.items():
    weights = {g: (5 if g in anchors else 1) for g in GENRES}; tot = sum(weights.values())
    for g in GENRES: rate[g] += films_per_rival_per_year * weights[g] / tot
print('Expected rival releases per year by genre (anchor weight 5, else 1; 9 rivals × 2 films/yr):')
for g in GENRES: print(f'- {g}: {rate[g]:.2f}')
mean_rate = sum(rate.values()) / len(GENRES)
print('\n| Window | mean genre | busiest (romance) | quietest (drama/crime) |')
print('|---|---|---|---|')
for label, weeks in (('same week', 1), ('2 weeks', 2), ('4 weeks', 4), ('8 weeks', 8), (f'{THEATRICAL_WEEKS}-week run-overlap', THEATRICAL_WEEKS)):
    p = lambda r: 1 - math.exp(-r * weeks / TICKS_PER_YEAR)
    print(f'| {label} | {p(mean_rate):.1%} | {p(rate["romance"]):.1%} | {p(rate["drama"]):.1%} |')

# ---------------------------------------------------------------- 4. survivorship
h('4. Rival survivorship under a constant annual terminal hazard (9 rivals, no replacements)')
print('| Annual hazard | expected survivors of 9 after 120 yr | after 71 yr (last entrant → 2040) |')
print('|---|---|---|')
for hz in (0.001, 0.002, 0.005, 0.01, 0.02, 0.05):
    print(f'| {hz:.1%} | {9*(1-hz)**120:.2f} | {9*(1-hz)**71:.2f} |')
print('\nAuthored arrival years:', [1920 + w // TICKS_PER_YEAR for w in RIVAL_ARRIVAL_WEEKS])

# ---------------------------------------------------------------- 5. net worth worked examples
h('5. Book Net Worth / Estimated Studio Value worked examples')
def example(name, cash, fac_capex, set_capex, loan, accrued, obligations, surplus3):
    book = cash + fac_capex * FACILITY_REFUND + set_capex * SET_REFUND - loan - accrued
    wind = book - HIRING_TERMINATION_FRACTION * obligations
    lo, hi = 3 * max(surplus3, 0) + cash - loan - accrued, 6 * max(surplus3, 0) + cash - loan - accrued
    lo_f, hi_f = max(lo, book), max(hi, book)   # floored at Book Net Worth (liquidation-bound)
    print(f'- **{name}**: Book Net Worth ${book:,.0f}; Guaranteed Obligations ${obligations:,.0f}; Wind-Down ${wind:,.0f}; '
          f'Estimated Value ${lo_f:,.0f}–${hi_f:,.0f}' + (' (liquidation-bound)' if lo < book else ''))
example('mid-game studio', 6_500_000, 4_400_000, 2_000_000, 5_000_000, 150_000, 10_769_231, 1_800_000)
example('hot, debt-funded studio', 2_000_000, 9_600_000, 4_200_000, 9_000_000, 300_000, 6_000_000, 3_200_000)
example('rich but declining studio', 30_000_000, 20_000_000, 5_714_286, 0, 0, 3_000_000, 1_500_000)

# ---------------------------------------------------------------- 6. fixed weekly cost of a 40-person studio
h('6. Fixed weekly cost sketch, 40 employees')
payroll = 40 * 75_000 / TICKS_PER_YEAR; overhead = OVERHEAD_BASE + OVERHEAD_PER_EMPLOYEE * 40
opex = 9_000 + 5_000 + 4_000 + 5_500; mortgage = weekly_payment(5_000_000, 0.08, 10)
total = payroll + overhead + opex + mortgage
print(f'- payroll ≈ ${payroll:,.0f}/wk (avg $75k/yr, hypothetical); overhead ${overhead:,.0f}; facility Opex ${opex:,.0f}; $5M/8%/10yr mortgage ${mortgage:,.0f}')
print(f'- total ≈ ${total:,.0f}/wk; 8-week liquidity line ≈ ${8*total:,.0f}')

# ---------------------------------------------------------------- 7. clean-shell scenario B
h('7. Scenario B — valuable distressed studio')
fac, sets, cash, debt = 9_700_000, 6_100_000, 15_015_000, 30_000_000
bv = fac * FACILITY_REFUND + sets * SET_REFUND + cash
print(f'- facility refund ${fac*FACILITY_REFUND:,.0f}; set refund ${sets*SET_REFUND:,.0f}; cash ${cash:,.0f}; book assets ${bv:,.0f}; debt ${debt:,.0f}; FRP ${bv-debt:,.0f}')
print(f'- liquidation recovers {bv/debt:.1%} of the debt; clean purchase after creditors settle = $0–1 nominal with a ${debt-bv:,.0f} creditor haircut')
