import hashlib,json,os
from pathlib import Path
S=Path('/Users/zacheryspector/studio-scratch');A=Path(__file__).parent;Q=S/'1370-c0-m0-config-bundle-metadata-disposable-controls-source-after-al-20261009-r1'
def role(p):
 p=Path(p);b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
p=Q/'RECIPE.json';assert role(p)['sha256']=='1aabfb01a918ff3aecbb791b26874e6ca208a9cb70b02e2def04127168987b92';v=json.loads(p.read_bytes());assert v['bounds']['wholeParentLaunchSeconds']==90
d={'schema':'1370-an-root-proposed-parent-clock-finding/v1','status':'SOURCE_PROPOSAL_HELD_NO_RUNTIME','recipe':role(p),'sourcePins':role(Q/'SOURCE-PINS.json'),'originalQualifiedWrapper':role(S/'1370-c0-b109-ascii-focused-route-source-after-al-20261009-r2/launch-focused-controls.py'),'originalRootLauncher':role(S/'1370-am-root-continuation-20261009-r1/run_b109_controls_once.py'),'finding':'Proposed recipe requires an already-qualified aggregate90-second parent orchestrator. The named original qualified parent mechanism direct-execs and does not implement such a separate outer clock. Original recorder implements child60/active75/whole90 starting in its own main. A new stronger parent promise is not an inherited requirement.','requiredRepair':'Preserve R1 and create a fresh recipe using actual original phases and ownership. Keep one aggregate child60/active75/whole90. If preparation is bounded, name its separate clock and cancel it before unchanged runtime; do not invent combined90 or extra outer watchdog. Review a concrete minimal direct-exec parent adapter before any separate grant.','executionAuthorization':False,'actualControlsRun':False,'oldR6StopPreserved':True}
p=A/'DISPOSABLE-PARENT-CLOCK-PREGRANT-FINDING.json'
with p.open('x') as f:json.dump(d,f,sort_keys=True,indent=2);f.write('\n');f.flush();os.fsync(f.fileno())
p.chmod(0o444);rr=role(p);print(json.dumps(rr))
b=(A/'LESSONS-r1.md').read_bytes();b+=b'''\n## Reuse the implemented clock, not a stronger draft promise\n\nThe next disposable-controls recipe proposed a ninety-second whole-parent clock and assumed an already-qualified parent orchestrator supplied it. Reading the actual accepted B109 root/wrapper source shows direct exec and owned-group recording, with sixty/seventy-five/ninety-second enforcement inside the recorder. No separate ninety-second parent clock exists there. The draft itself is held; no grant or test was executed. Preserve the original proposal and correct a fresh derivative to authentic phase scopes. If bounded preparation is needed, keep it explicit and separate from unchanged runtime. Do not build another outer watchdog merely to satisfy a draft overstatement. This recurring integration risk is why clock inheritance must be checked against executable source, even after an earlier similar lesson was recorded.\n'''
p=A/'LESSONS-r2.md'
with p.open('xb') as f:f.write(b);f.flush();os.fsync(f.fileno())
p.chmod(0o444);print(json.dumps(role(p)))
