import datetime,hashlib,json,os,subprocess
from pathlib import Path
S=Path('/Users/zacheryspector/studio-scratch');A=Path(__file__).parent;R=Path('/Users/zacheryspector/The-Movies-headless-program')
def role(p):
 p=Path(p);b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
publication=S/'1370-am-checkpoint-root-finalization-20261009-r1/PUSH-READBACK.json';diagnosis=S/'1370-an-m0-r6-config-resolution-independent-source-diagnosis-20261009-r1/DIAGNOSIS.json'
assert role(publication)['sha256']=='a7ca327d2d4610704f426630d79343722fb92c19f3762dd521221d77a567479b' and role(diagnosis)['sha256']=='97f3d4d0a72d4d0d4379ad7363187e4e31e886ed769c83df4de34d354b423f81'
def git(*args):return subprocess.check_output(['git','-c','gc.auto=0','-c','maintenance.auto=0','--no-optional-locks',*args],cwd=R,timeout=120).decode().strip()
assert git('rev-parse','HEAD')=='7087f116cf998fd86e33fb8e004df628e0686dbd' and git('rev-parse','HEAD:src')=='13880d9b0ba72aff5d4c5bcf5d12fe682c5de554' and git('status','--porcelain')==''
d={'schema':'1370-an-root-continuation-start/v1','utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'publishedPredecessor':role(publication),'sourceDiagnosis':role(diagnosis),'sourceDiagnosisAdoptedAtSourceScope':True,'executionAuthorization':False,'actualCapturedTemporaryFileEvent':False,'exclusiveCauseClaim':False,'m0TypesAccepted':False,'currentM0FullPreservationAccepted':False,'oldR6StopPreserved':True,'currentProductionHead':'7087f116cf998fd86e33fb8e004df628e0686dbd','currentSourceTree':'13880d9b0ba72aff5d4c5bcf5d12fe682c5de554','next':'Review real nested-loader disposable RED/GREEN source and qualified parent route, run once after genuine current bindings; separately establish complete current M0 content/nonroot metadata and explicitly qualify known root drift before any fresh M0 route.'}
p=A/'START.json'
with p.open('x') as f:json.dump(d,f,sort_keys=True,indent=2);f.write('\n');f.flush();os.fsync(f.fileno())
p.chmod(0o444);print(json.dumps(role(p)))
text='''# Lessons after published AM\n\nAM7087f116 is pushed and independently checked against GitHub, its AL parent and unchanged source tree. The checkpoint backs up the admitted natural208 capture, all sixteen complete-vector renewal calculations, unfavorable encoder evidence, the pre-R6 preservation proof, both failed type routes, and all major lessons through r22. A clean published checkpoint is a durable baseline; later work must use that actual HEAD rather than stale AL operational authority.\n\n## Distinguish a mandatory source path from a captured file event\n\nIndependent diagnosis97f3d4d0 authenticates the actual R6 command/cwd, three historical config/package blobs and the installed nested loader. With no root/config override, the real Vitest2 path selects the mirror root config; its .ts extension and nearest type-module package select the Vite5 ESM path, which awaits a timestamped sibling write before a successful import and then requests unlink. This supports a mandatory source-backed transient write under the authenticated route assumptions. It is stronger than a generic guess about possible caching, but does not invent the exact filename, a captured filesystem event or proof that no other contributor changed the root. The workspace itself uses inline projects without extends; do not misattribute workspace bundling.\n\nThis diagnosis does not retroactively pass R6 or replace absent M0 after-proofs. Complete actual content/nonroot metadata verification, explicit treatment of the known root drift, disposable real-loader RED/GREEN, and independent review remain required before fresh M0 acceptance. Move tooling writes outside protected roots while retaining all configuration resolution and collection semantics.\n'''
p=A/'LESSONS-r1.md'
with p.open('x') as f:f.write(text);f.flush();os.fsync(f.fileno())
p.chmod(0o444);print(json.dumps(role(p)))
