import {stableStringify,importSave,validateSave,makeSave,exportCurrentState} from './src/core/save.ts';
import {industryPage,industrySummary} from './bridge/industry.ts';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {setImmediate as yieldNow} from 'node:timers/promises';
import {cpus,totalmem,platform,release,arch} from 'node:os';
import {getHeapStatistics} from 'node:v8';
const dir=process.argv[2],sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
const assert=(x:unknown,m:string)=>{if(!x)throw Error(m)};
const fixtures=[{label:'all-nine-entry',path:'/tmp/p12a-engineering-8788-P6KEMm/week-2548.save.json'},{label:'full-target-after-6240',path:'/tmp/p12a-core-resume-t7c16t09/week-8788.save.json',sha256:'cd0e3836332c4b4ffd87e637381c2d5e2d1e4c9db976c4df47b8683550de56d9'}];
assert(!existsSync(dir+'/RUN-STARTED.json'),'Existing run');writeFileSync(dir+'/RUN-STARTED.json',JSON.stringify({pid:process.pid,at:new Date().toISOString()}),{flag:'wx',mode:0o600});
const manifest=JSON.parse(readFileSync(dir+'/source-before.json','utf8'));let stopped=false;process.on('SIGTERM',()=>stopped=true);process.on('SIGINT',()=>stopped=true);
const report:any={order:'OPS-P12A-LIVING-HOLLYWOOD-20260910-05',kind:'fixed-fixture-phase-sampler',startedAt:new Date().toISOString(),completed:false,binding:JSON.parse(readFileSync(dir+'/binding.json','utf8')),hardware:{platform:platform(),release:release(),arch:arch(),cpu:cpus()[0]?.model,logicalCpus:cpus().length,totalMemoryBytes:totalmem(),heapSizeLimit:getHeapStatistics().heap_size_limit},runtime:{node:process.version,executable:process.execPath,execArgv:process.execArgv,nodeOptionsPresent:!!process.env.NODE_OPTIONS},warmups:3,repetitions:20,percentile:'nearest-rank observed p95 (sorted index ceil(.95*n)-1); empirical n20, not population guarantee',fixtures:[],errors:[],qualification:'Synthetic read-only fixed fixtures using current compiled production functions. Pure phases are isolated from runtime storage; no engine/Unity/native claim. Source fixture files are only read. No forced GC. No new authoritative advances or stress12 claim.'};
const persist=()=>writeFileSync(dir+'/report-progress.json',JSON.stringify(report,null,2)+'\n',{mode:0o600});
const summary=(a:number[])=>{const v=[...a].sort((a,b)=>a-b);return {n:v.length,medianMs:(v[(v.length-1)>>1]+v[v.length>>1])/2,p95Ms:v[Math.ceil(v.length*.95)-1],maxMs:v.at(-1),minMs:v[0]}};
async function phase(row:any,name:string,fn:()=>unknown,check:(v:any)=>void=()=>{}){const samples:any[]=[],warmups:any[]=[];let out:any;for(let i=-3;i<20;i++){if(stopped||existsSync(dir+'/PAUSE'))throw Error('Interrupted before next phase sample');const before=process.memoryUsage(),start=performance.now();out=fn();const elapsedMs=performance.now()-start;const after=process.memoryUsage();check(out);const v={elapsedMs,heapBefore:before.heapUsed,heapAfter:after.heapUsed,rssAfter:after.rss};(i<0?warmups:samples).push(v);out=null;await yieldNow()}row.phases.push({name,warmups,samples,...summary(samples.map(x=>x.elapsedMs))});persist();console.log(JSON.stringify({fixture:row.label,phase:name,...summary(samples.map(x=>x.elapsedMs))}));}
try{for(const f of fixtures){const bytes=readFileSync(f.path),digest=sha(bytes);assert(!f.sha256||digest===f.sha256,'Fixture hash changed');const json=bytes.toString('utf8'),parsed=importSave(json);assert(parsed.saveVersion===19,'Wrong saveVersion');const state:any=parsed.state,h=state.hollywood;assert(stableStringify(parsed)===json,'Fixture is not canonical');const measuredSave=makeSave(state);assert(stableStringify(measuredSave)===json,'Current exporter changed fixture');
const row:any={label:f.label,path:f.path,sha256:digest,bytes:bytes.length,seed:state.seed,week:state.market.tick,counts:{rivals:h.businesses.length,films:h.films.length,liveFilms:h.films.filter((v:any)=>v.provenance==='simulation/v1').length,careerEvents:h.careerEvents.length,employment:h.employment.length,receipts:h.receipts.length,people:state.talent.length,activeProjects:h.businesses.reduce((n:number,b:any)=>n+b.productions.length,0)},phases:[]};report.fixtures.push(row);persist();
await phase(row,'canonical-serialize-already-validated-detached-save',()=>stableStringify(measuredSave),v=>assert(v===json,'Serialization differs'));
await phase(row,'sha256-existing-canonical-utf8-string',()=>sha(json),v=>assert(v===digest,'Digest differs'));
await phase(row,'canonical-serialize-plus-sha256-paired',()=>sha(stableStringify(measuredSave)),v=>assert(v===digest,'Paired digest differs'));
await phase(row,'strict-validate-already-parsed-v19',()=>validateSave(parsed),v=>assert(v.saveVersion===19,'Validation version'));
await phase(row,'parse-and-strict-import-v19',()=>importSave(json),v=>assert(v.state.market.tick===state.market.tick,'Import week differs'));
await phase(row,'makeSave-detach-and-strict-validate',()=>makeSave(state),v=>assert(v.state.market.tick===state.market.tick,'makeSave week differs'));
await phase(row,'complete-export-current-state',()=>exportCurrentState(state),v=>assert(v===json,'Complete export differs'));
const query:any={requestId:'fixed-perf',view:'studio',targetId:h.businesses[0].studioId,page:0,pageSize:50,lane:'recent',period:'all'};const coldStart=performance.now(),coldPage=industryPage(state,'fixed-perf-session',0,query);row.firstUncachedIndustryPageMs=performance.now()-coldStart;row.firstPageUtf8Bytes=Buffer.byteLength(JSON.stringify(coldPage));
await phase(row,'indexed-studio-profile-first-page-50',()=>industryPage(state,'fixed-perf-session',0,query),v=>assert(v.films.length<=50,'Page bound'));
await phase(row,'cached-industry-summary',()=>industrySummary(state));
const size=(v:any)=>Buffer.byteLength(stableStringify(v));const components=Object.fromEntries(Object.entries(h).map(([k,v])=>[k,size(v)]));const businessBytes=h.businesses.map((b:any)=>({studioId:b.studioId,bytes:size(b),components:Object.fromEntries(Object.entries(b).map(([k,v])=>[k,size(v)]))}));const filmSizes=h.films.map(size);const actualNonPlayerPeople=new Set(h.identities.filter((s:any)=>s.role!=='player').flatMap((s:any)=>state.talent.filter((t:any)=>t.id.startsWith('person-'+s.studioId+'-')).map((t:any)=>t.id)));const sharedPeople=state.talent.filter((t:any)=>actualNonPlayerPeople.has(t.id));
row.storageComponents={unit:'uncompressed canonical UTF-8 bytes',hollywoodRootBytes:size(h),exactWholeSaveIncrementForHollywoodRoot:bytes.length-size({...parsed,state:Object.fromEntries(Object.entries(state).filter(([k])=>k!=='hollywood'))}),rootComponents:components,businessBytes,filmRows:{n:filmSizes.length,sum:filmSizes.reduce((a:number,b:number)=>a+b,0),average:filmSizes.reduce((a:number,b:number)=>a+b,0)/filmSizes.length,max:Math.max(...filmSizes)},p12AddedSharedPeople:{identityRule:'talent.id exact person-<non-player canonical studioId>- prefix minted by Hollywood; includes all matched shared talent records even if later departed',count:sharedPeople.length,bytes:size(sharedPeople)},typedHistorySelectedSumBytes:['careerEvents','employment','receipts'].reduce((n,k)=>n+components[k],0),qualifications:['Component array punctuation is counted in each component value; per-row sums omit array punctuation.','Exact Hollywood root delta is whole canonical Save minus hypothetical field omission used only for size attribution; no such reduced Save is written/imported.','Added shared people are reported separately, not silently summed with potentially overlapping Hollywood career-credit references.','No permanent film/person/history/receipt record removed. These are full-target9-rival measurements, not synthetic12 stress.']};
assert(sha(readFileSync(f.path))===digest,'Protected fixture changed');persist();}
report.completed=true;
}catch(error){report.errors.push({message:(error as Error).message,stack:String((error as Error).stack).split('\n').slice(0,6)});process.exitCode=1}
finally{report.sourceChanges=manifest.filter((r:any)=>sha(readFileSync(r.absolutePath))!==r.sha256).map((r:any)=>r.path);if(report.sourceChanges.length){report.completed=false;process.exitCode=1}report.finishedAt=new Date().toISOString();report.processMemory={...process.memoryUsage(),processHighWaterRssKiB:process.resourceUsage().maxRSS};writeFileSync(dir+'/report.json',JSON.stringify(report,null,2)+'\n',{mode:0o600});persist();console.log(JSON.stringify({completed:report.completed,errors:report.errors,sourceChanges:report.sourceChanges,dir}));}
