from pathlib import Path
import json,hashlib,stat,datetime
S=Path('/Users/zacheryspector/studio-scratch');P=Path(__file__).resolve().parent;M=P/'BACKUP-MANIFEST-DRAFT.json';j=json.loads(M.read_text());a=j['archiveCandidates'];known={x['source'] for x in a+j['localOnlyHashSize']};prefix='docs/engineering/playability-launch-review/evidence/p14b4-20260919/1370-ag-materialization-and-b-causal-outcomes/'
roots=[S/n for n in ['1370-c0-three-employment-preimages-filled-roles-20261009-r1','1370-c0-three-employment-filled-roles-independent-exact-review-20261009-r1','1370-c0-three-employment-preimages-comparison-20261009-r1','1370-c0-three-employment-preimages-observed-independent-review-20261009-r1','1370-c0-b109-bounded-json-optimization-proposal-20261009-r2','1370-c0-b109-bounded-json-optimization-independent-source-review-20261009-r2']]
for root in roots:
 for p in sorted(root.iterdir()):
  if str(p) in known:continue
  st=p.lstat();assert stat.S_ISREG(st.st_mode) and st.st_nlink==1;raw=p.read_bytes();assert not any(mark in raw for mark in [b'/Applications/Google Chrome',b'/Applications/Slack',b'/Applications/Spotify']);rel=str(p.relative_to(S));a.append({'source':str(p),'relativePath':rel,'proposedRepositoryPath':prefix+rel,'sha256':hashlib.sha256(raw).hexdigest(),'bytes':len(raw),'gitBlobOid':hashlib.sha1(('blob '+str(len(raw))+'\0').encode()+raw).hexdigest(),'device':st.st_dev,'inode':st.st_ino,'mode':stat.S_IMODE(st.st_mode),'links':st.st_nlink})
 rec=next((x for x in j['sourceGroups'] if x['sourceRoot']==str(root)),None);vals=[x for x in a if str(Path(x['source']).parent)==str(root)];d={'sourceRoot':str(root),'archiveFiles':len(vals),'archiveBytes':sum(x['bytes'] for x in vals),'localOnly':0,'priorReferences':0}
 if rec:rec.update(d)
 else:j['sourceGroups'].append(d)
j['EmploymentComparisonObserved']={'receiptPath':str(S/'1370-c0-three-employment-preimages-observed-independent-review-20261009-r1/RECEIPT.json'),'receiptSha256':'faf6df1cb38011ff74b7fbbca9c712da242d13cc6b15f8581dc1f1019202cb3d','reportSha256':'b419fd0eea96ce9f646842fefeb7b1cc028a0dd07ee1146aca4892e36a47be1c','actualToolChunkId':'a7a728','actualExit':0,'HToAging':{'shared':44,'changed':39,'unchanged':5,'leftOnly':0,'rightOnly':0},'AgingToM0':{'shared':39,'changed':8,'unchanged':31,'leftOnly':5,'rightOnly':5},'changedFieldsOnSharedOnly':['annualSalary','signingBonus'],'sharedLifecycleChanges':0,'firstUnmatchedAgingToM0SourceOrder':24,'causalAcceptance':False}
j['pending']=[x for x in j['pending'] if 'employment' not in x['role'].lower()]
for x in j['pending']:x['status']='Frozen r2source6c152d46 and conditional static20163ef5 included; root actual recorder14/encoder11 controls then separate bounded benchmark pending.'
j['status']='DRAFT_R9_AND_EMPLOYMENT_COMPARISON_ACCEPTED_OPTIONAL_BENCHMARK_PENDING';j['utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();M.write_text(json.dumps(j,sort_keys=True,indent=2)+'\n')
s=json.loads((P/'INVENTORY-SUMMARY-DRAFT.json').read_text());s.update(status=j['status'],archiveFiles=len(a),archiveBytes=sum(x['bytes'] for x in a),roots=len(j['sourceGroups']),pendingRoles=len(j['pending']),addedArchiveFilesSinceR2=len(a)-623);(P/'INVENTORY-SUMMARY-DRAFT.json').write_text(json.dumps(s,sort_keys=True,indent=2)+'\n')
facts='Artifact-only three-employment comparison actual0 in0.695s/reportb419fd0e.../independentfaf6df1c... is accepted descriptively. H→aging:44 shared,39 salary+bonus changed/five unchanged/no unmatched. Aging→M0:39 shared,eight salary+bonus changed/31 unchanged,plus five left-only and five right-only identities. Shared lifecycle fields and source-order indices match; ten unmatched rows stay separately accounted. First H→aging salary change is row0 394607→395548. First aging→M0 shared salary change is row26 346793→370607; earliest unmatched source-order24/person-r01-0 changes r02 to r03 contract. No terminal ordering difference identifies a mutation time or cause.'
p=P/'1370-AG-OUTCOME-DRAFT.md';t=p.read_text().replace('actual three-employment comparison and any ready benchmark are pending before final checkpoint pins.','the actual three-employment comparison is independently accepted descriptively; any ready benchmark remains pending before final checkpoint pins.').replace('actual comparison is pending, using newly accepted R9 observed frame d681f73e... with all44 exact4cff rows.',facts).replace('Next: parent adopts qualified R9 observed result, runs/reviews the accepted label-neutral employment comparison, and finalizes today’s backup checkpoint with any ready independently qualified bounded benchmark.','Next: parent adopts the descriptive comparison and finalizes today’s backup checkpoint with any ready independently qualified bounded benchmark. Subsequent separate causal slices trace initial week0 row0 exact quote inputs/calculation (H→aging) and earliest unmatched week208/person-r01-0 replacement assignment at row24 (aging→M0), retaining inputs/order/eligibility/selection before attributing a cause.').replace('r2 controls/benchmark remain separately gated.','frozen r2source6c152d46.../conditional static20163ef5... repairs those recorder findings; actual14-recorder/11-encoder controls and benchmark remain separately gated.');p.write_text(t)
p=P/'HANDOFF-DRAFT.md';t=p.read_text().replace('final pins/commit remain held for the artifact comparison and any ready bounded benchmark.','final pins/commit remain held only for any ready bounded benchmark.').replace('- Label-neutral three-employment adapter r2 MANIFESTc9e95626.../independent97419996... is source-only accepted. Actual comparison is unrun and requires an independently accepted current aging-era frame plus complete44-row4cff bytes. Compare H→aging and aging→M0 separately.','- '+facts).replace('2. Parent adopts qualified R9 observed result, then runs accepted label-neutral three-employment comparison with exact filled frame/receipt roles. Independently interpret full44-row fields and H→aging/aging→M0 source-occurrence joins; no extra full scan for artifact-only comparison.','2. Parent adopts independent descriptive comparison faf6df1c...; no extra full scan for artifact-only comparison. Subsequent bounded causal slices remain separate: initial week0 row0 exact quote provenance/calculation for H→aging, and earliest unmatched week208/person-r01-0 replacement inputs/order/eligibility/selection at row24 for aging→M0. No cause is invented.').replace('R2 is being authored; no acceptance/benchmark result invented.','Frozen r2source6c152d46.../conditional static20163ef5... is included. Actual14-recorder/11-encoder controls and benchmark remain separately gated; no observed result is invented.')
import re
t=re.sub(r'Current draft\d+files/[\d,]+bytes',f"Current draft{s['archiveFiles']}files/{s['archiveBytes']:,}bytes",t);p.write_text(t)
p=P/'BACKUP-ACTIONS-DRAFT.md';t=p.read_text();t=re.sub(r'The read-only draft contains \d+ exact source/evidence files across \d+ selected groups \([\d,]+ bytes\)',f"The read-only draft contains {s['archiveFiles']} exact source/evidence files across {s['roots']} selected groups ({s['archiveBytes']:,} bytes)",t).replace('Add the root\'s observed adoption and completed three-employment comparison/independent interpretation, plus any ready qualified benchmark, before final pins.','The parent observed adoption, exact filled roles, completed three-employment comparison and independent descriptive acceptance faf6df1c... are included. Add any ready qualified benchmark before final pins.');p.write_text(t)
print(json.dumps(s,sort_keys=True))
