from pathlib import Path
import os,json,hashlib,stat,datetime
S=Path('/Users/zacheryspector/studio-scratch');P=Path(__file__).resolve().parent
M=P/'BACKUP-MANIFEST-DRAFT.json';j=json.loads(M.read_text());a=j['archiveCandidates'];local=j['localOnlyHashSize'];prefix='docs/engineering/playability-launch-review/evidence/p14b4-20260919/1370-ag-materialization-and-b-causal-outcomes/'
roots=[S/'1370-c0-aging-era-employment-witness-r9-observed-independent-review-20261009-r1',S/'1370-c0-aging-era-witness-r7-parent-guard-preparation-20261008-r2/evidence/postflight-r9-20261009-r1']
known={x['source'] for x in a+local}
for root in roots:
 for p in sorted(root.iterdir()):
  if str(p) in known:continue
  assert p.is_file() and not p.is_symlink();st=p.lstat();assert st.st_nlink==1;raw=p.read_bytes();h=hashlib.sha256(raw).hexdigest();rel=str(p.relative_to(S))
  if p.name in {'BEFORE-PS.txt','AFTER-PS.txt','BEFORE-LSOF.bin','AFTER-LSOF.bin'}:
   local.append({'source':str(p),'relativePath':rel,'sha256':h,'bytes':len(raw),'reason':'Raw machine-wide process/FD enumeration retained locally; hash/size only.'})
  else:
   # Named final evidence contains typed project/metadata/identity facts, never global process rows.
   assert not any(mark in raw for mark in [b'/Applications/Google Chrome',b'/Applications/Slack',b'/Applications/Spotify'])
   a.append({'source':str(p),'relativePath':rel,'proposedRepositoryPath':prefix+rel,'sha256':h,'bytes':len(raw),'gitBlobOid':hashlib.sha1(('blob '+str(len(raw))+'\0').encode()+raw).hexdigest(),'device':st.st_dev,'inode':st.st_ino,'mode':stat.S_IMODE(st.st_mode),'links':st.st_nlink})
for root in roots:
 rec=next((x for x in j['sourceGroups'] if x['sourceRoot']==str(root)),None)
 vals=[x for x in a if str(Path(x['source']).parent)==str(root)];loc=[x for x in local if str(Path(x['source']).parent)==str(root)]
 d={'sourceRoot':str(root),'archiveFiles':len(vals),'archiveBytes':sum(x['bytes'] for x in vals),'localOnly':len(loc),'priorReferences':0}
 if rec:rec.update(d)
 else:j['sourceGroups'].append(d)
j['R9ActualCandidateWin']['finalFullPostAndObservedAcceptancePending']=False
j['R9ObservedAcceptance']={'path':str(roots[0]/'RECEIPT.json'),'sha256':'d681f73e3613248c7ccd0be7736e46bd1fe424dd62ea099a60e031e774238f64','decision':'ACCEPT_OBSERVED_AGING_ERA_EMPLOYMENT_PREIMAGE','fullPostflightSha256':'555867b2be0abf76728fc8b905c52a73512b5da31d24162d804e7e1b9d8c9347','fullPostflightPinsSha256':'3952c8f763bbe30b0cde00123bc89103516157fc4bea30208561c9273bf6a715','fullImmutableEqualsBeforeAndImmediatePreRun':True,'externalNumericOwnedPgid':None,'externalNumericGroupProbeClaim':False}
j['pending']=[x for x in j['pending'] if 'R9' not in x.get('role','') or 'comparison' in x.get('role','').lower()]
for x in j['pending']:
 if 'employment' in x['role'].lower():x['status']='ObservedR9receipt d681 qualifies exact frame roles; root artifact comparison/independent interpretation pending.'
j['status']='DRAFT_R9_OBSERVED_ACCEPTED_COMPARISON_AND_OPTIONAL_READY_BENCHMARK_PENDING';j['utc']=datetime.datetime.now(datetime.timezone.utc).isoformat()
# Refresh finite owned evidence identities; no runtime or copied-root traversal.
for x in a:
 p=Path(x['source']);raw=p.read_bytes();st=p.lstat();assert stat.S_ISREG(st.st_mode) and st.st_nlink==1
 x.update(sha256=hashlib.sha256(raw).hexdigest(),bytes=len(raw),gitBlobOid=hashlib.sha1(('blob '+str(len(raw))+'\0').encode()+raw).hexdigest(),device=st.st_dev,inode=st.st_ino,mode=stat.S_IMODE(st.st_mode),links=st.st_nlink)
M.write_text(json.dumps(j,sort_keys=True,indent=2)+'\n')
s=json.loads((P/'INVENTORY-SUMMARY-DRAFT.json').read_text());s.update(status=j['status'],archiveFiles=len(a),archiveBytes=sum(x['bytes'] for x in a),roots=len(j['sourceGroups']),localOnlyFiles=len(local),pendingRoles=len(j['pending']),addedArchiveFilesSinceR2=len(a)-623,newContentClassifiedLocalOnly=len(local)-25);(P/'INVENTORY-SUMMARY-DRAFT.json').write_text(json.dumps(s,sort_keys=True,indent=2)+'\n')
pr=json.loads((P/'PRIVACY-CONTENT-REVIEW-DRAFT.json').read_text());pr['localOnlyTotal']=len(local);pr['newLocalOnlyPaths']=[x['relativePath'] for x in local[25:]];(P/'PRIVACY-CONTENT-REVIEW-DRAFT.json').write_text(json.dumps(pr,sort_keys=True,indent=2)+'\n')
h=P/'HANDOFF-DRAFT.md';t=h.read_text().replace('final pins/commit remain held for R9 actual outcome and postflight.','final pins/commit remain held for the artifact comparison and any ready bounded benchmark.').replace('R9 actual historical witness produced a valid candidate frame; final observed acceptance is pending the completed full postflight. No phase/runtime/ledger completion is implied.','R9 actual historical employment preimage is independently accepted d681f73e... after the completed full postflight. No phase/runtime/ledger completion is implied.').replace('Frame and raw preimage are preserved in r9 observed reviewr1; receipt remains pending full guard.','Frame and raw preimage are preserved in r9 observed reviewr1; receipt d681f73e... qualifies exact comparator roles.').replace('- Parent sole full postguardtool80695 is running output `postflight-r9-20261009-r1` againstb087ec..., no owned numeric CSV. Do not read unfinished output. Independently authenticate complete protected/dependency/root bytes+metadata/current worker absence and explicit numeric limitation before final observed receipt usable by comparison.','- Actual full postguard80695exit0 (438.806s,total;338.403s inventory), snapshot555867b2.../PINS3952c8f7.../parent5edcda79..., equals bothb087ec... and fresh9462f60e.... Independent bounded current checks passed; accepted receipt d681f73e... explicitly leaves external R9PGIDnull.').replace('1. Finish roottool80695 full postguard and independently authenticate completed proof againstb087ec..., current workers and no external numeric R9PGID claim. Issue positive observed receipt only then, with exact framePath/frameSha256/qualifiedSourceSha3aaf roles. Preserve overnight REFINE and earlier STOPs.','1. Parent adopts independently accepted R9 observed receipt d681f73e... with exact framePath/frameSha256/qualifiedSourceSha3aaf roles. Completed fullpost555867b2... equals beforeb087ec... and fresh pre-run9462f60e...; no external numeric R9PGID is claimed. Preserve overnight REFINE and earlier STOPs.').replace('Current draft1217files/105,687,155bytes plus97 prior references/43 local raw process-FD hash-size entries grows only with finalized postflight/comparison/ready benchmark evidence.',f"Current draft{s['archiveFiles']}files/{s['archiveBytes']:,}bytes plus97 prior references/{s['localOnlyFiles']} local raw process-FD hash-size entries grows only with finalized comparison/ready benchmark evidence.")
h.write_text(t)
(P/'BACKUP-ACTIONS-DRAFT.md').write_text(f'''# Finite parent checkpoint actions — R9 observed accepted; artifact comparison pending\n\nThe read-only draft contains {s['archiveFiles']} exact source/evidence files across {s['roots']} selected groups ({s['archiveBytes']:,} bytes), 97 verified prior checkpoint references and {s['localOnlyFiles']} local-only raw process/FD hash-size entries. R9 observed receipt d681f73e... authenticates the exact 44-row historical employment frame plus completed fullpost555867... equal to both originalb087 and fresh pre-run9462. No external numeric R9PGID is claimed. Add the root's observed adoption and completed three-employment comparison/independent interpretation, plus any ready qualified benchmark, before final pins. No extra full inventory is needed for artifact-only comparison.\n\nPreserve all earlier source/refinement/control/exact/archive/adoption/actual/STOP evidence, especially R7 unknown cause, R8 first Git null-device cause and B109 timeout. Keep complete one-tick scientific outputs/both202-file mirrors and B109 partialgzip/sole206-file mirror. Never vendor the materialized runtime root, dependencies, private Git or caches. Machine-wide process/FD dumps and any embedded unrelated private application enumeration stay local with hash/size only.\n\nOnce no protected lane is active, the sole parent production writer copies exactly finalized manifest records to the established1370AG archive, verifies hashes/modes/blob identities and truthful exclusions/reference roles, applies final1370AG/HANDOFF, tracks intended ignored evidence, reviews diff/status, commits/pushes and verifies advertised refs plus archive readback. This proposal does not claim GitHub already contains these bytes.\n\nA docs-only checkpoint changes HEAD and whole production protected digest. Any later lane requires explicit predecessor/new-HEAD adoption and refreshed external guards; old production payload hashes never certify new docs. The unchanged historical copy stays immutable and is not automatically rematerialized. No phase gate, source review or actual admission is waived.\n''')
print(json.dumps(s,sort_keys=True))
